import random
from typing import NamedTuple, Optional, List
from BaseClasses import Item, Region, ItemClassification


class LK2Item(Item):
    name: str
    id: int

    def __init__(self, name: str, classification: ItemClassification, item_id, player: int):
        super(LK2Item, self).__init__(name, classification, item_id, player=player)

        self.name = name
        self.id = item_id



lost_kingdoms_2_items = {}

lost_kingdoms_2_key_items = [
    "Red Key", "Blue Key", "Green Key", "Fossil Head", "Fossil Torso", "Fossil Tail", "Fossil Rt Wing", "Fossil Lt Wing",
    "Fossil Rt Arm", "Fossil Lt Arm", "Fossil Rt Leg", "Fossil Lt Leg", "Bottle", "Black Liquid", "Mysterious Key", "Blade of Skill",
    "Blade of Power", "Blade of Wisdom", "Blade of Time", "Jewel of Alanjeh", "Eno Runestone", "Oht Runestone", "Elise Runestone",
    "Olf Runestone", "Ebin Runestone", "Keil Runestone", "Nebeth Runestone", "Stone of Sealing", "Castle Gate Key", "Key to Fountain"
]

lost_kingdoms_2_cards = {
    'Skeleton': {'DolphinAddress': '802589a6', 'element': 'Earth', 'hexCode': '01', 'isKeyCard': 0, 'isShopCard': 1, 'number': 1, 'orderInMemory': 0, 'rarity': 1, 'type': 'Independent', 'hasCombo': 1, 'price': 30, 'mana_cost': 1},
    'Ghost Armor': {'DolphinAddress': '802589ba', 'element': 'Wood', 'hexCode': '02', 'isKeyCard': 0, 'isShopCard': 1, 'number': 2, 'orderInMemory': 1, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 720, 'mana_cost': 4},
    'Red Dragon': {'DolphinAddress': '802589ce', 'element': 'Fire', 'hexCode': '03', 'isKeyCard': 0, 'isShopCard': 1, 'number': 3, 'orderInMemory': 2, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 2700, 'mana_cost': 10},
    'Lizardman': {'DolphinAddress': '802589f6', 'element': 'Earth', 'hexCode': '05', 'isKeyCard': 0, 'isShopCard': 1, 'number': 4, 'orderInMemory': 4, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 50, 'mana_cost': 2},
    'Mandragora': {'DolphinAddress': '80258a5a', 'element': 'Wood', 'hexCode': '0A', 'isKeyCard': 1, 'isShopCard': 1, 'number': 5, 'orderInMemory': 9, 'rarity': 1, 'type': 'Helper', 'hasCombo': 1, 'price': 45, 'mana_cost': 1},
    'Elephant': {'DolphinAddress': '80259216', 'element': 'Earth', 'hexCode': '6d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 6, 'orderInMemory': 108, 'rarity': 1, 'type': 'Summons', 'hasCombo': 1, 'price': 90, 'mana_cost': 4},
    'Red Lizard': {'DolphinAddress': '80258a6e', 'element': 'Fire', 'hexCode': '0B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 7, 'orderInMemory': 10, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 100, 'mana_cost': 3},
    'Unicorn': {'DolphinAddress': '80258a82', 'element': 'Wood', 'hexCode': '0C', 'isKeyCard': 0, 'isShopCard': 1, 'number': 8, 'orderInMemory': 11, 'rarity': 7, 'type': 'Transform', 'hasCombo': 0, 'price': 5400, 'mana_cost': 4},
    'Hobgoblin': {'DolphinAddress': '80258a96', 'element': 'Fire', 'hexCode': '0D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 9, 'orderInMemory': 12, 'rarity': 1, 'type': 'Independent', 'hasCombo': 1, 'price': 30, 'mana_cost': 1},
    'Sand Golem': {'DolphinAddress': '80258abe', 'element': 'Earth', 'hexCode': '0F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 10, 'orderInMemory': 14, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 300, 'mana_cost': 7},
    'Jack-O-Lantern': {'DolphinAddress': '80258ad2', 'element': 'Fire', 'hexCode': '10', 'isKeyCard': 0, 'isShopCard': 0, 'number': 11, 'orderInMemory': 15, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 11},
    'Man Trap': {'DolphinAddress': '80258afa', 'element': 'Wood', 'hexCode': '12', 'isKeyCard': 0, 'isShopCard': 1, 'number': 12, 'orderInMemory': 17, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 1},
    'Sand Worm': {'DolphinAddress': '80258b22', 'element': 'Earth', 'hexCode': '14', 'isKeyCard': 0, 'isShopCard': 1, 'number': 13, 'orderInMemory': 19, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 600, 'mana_cost': 7},
    'Mummy': {'DolphinAddress': '80258b36', 'element': 'Earth', 'hexCode': '15', 'isKeyCard': 0, 'isShopCard': 1, 'number': 14, 'orderInMemory': 20, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 225, 'mana_cost': 1},
    'Cockatrice': {'DolphinAddress': '80258b4a', 'element': 'Wood', 'hexCode': '16', 'isKeyCard': 0, 'isShopCard': 1, 'number': 15, 'orderInMemory': 21, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 750, 'mana_cost': 4},
    'Sasquatch': {'DolphinAddress': '80258b5e', 'element': 'Water', 'hexCode': '17', 'isKeyCard': 0, 'isShopCard': 1, 'number': 16, 'orderInMemory': 22, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 2200, 'mana_cost': 6},
    'Wraith': {'DolphinAddress': '80258b72', 'element': 'Water', 'hexCode': '18', 'isKeyCard': 0, 'isShopCard': 1, 'number': 17, 'orderInMemory': 23, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 1, 'price': 300, 'mana_cost': 4},
    'Orc': {'DolphinAddress': '80258b86', 'element': 'Fire', 'hexCode': '19', 'isKeyCard': 0, 'isShopCard': 1, 'number': 18, 'orderInMemory': 24, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 135, 'mana_cost': 3},
    'Fairy': {'DolphinAddress': '80258bae', 'element': 'Water', 'hexCode': '1B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 19, 'orderInMemory': 26, 'rarity': 1, 'type': 'Helper', 'hasCombo': 1, 'price': 240, 'mana_cost': 3},
    'Vampire Bush': {'DolphinAddress': '80259202', 'element': 'Fire', 'hexCode': '6c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 20, 'orderInMemory': 107, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 690, 'mana_cost': 3},
    'Catoblepas': {'DolphinAddress': '80258bfe', 'element': 'Earth', 'hexCode': '1F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 21, 'orderInMemory': 30, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 900, 'mana_cost': 5},
    'Kraken': {'DolphinAddress': '80258c12', 'element': 'Water', 'hexCode': '20', 'isKeyCard': 0, 'isShopCard': 1, 'number': 22, 'orderInMemory': 31, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 3300, 'mana_cost': 6},
    'Water Reaper': {'DolphinAddress': '80258c26', 'element': 'Water', 'hexCode': '21', 'isKeyCard': 0, 'isShopCard': 1, 'number': 23, 'orderInMemory': 32, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 45, 'mana_cost': 1},
    'Fenril': {'DolphinAddress': '80258c3a', 'element': 'Wood', 'hexCode': '22', 'isKeyCard': 0, 'isShopCard': 1, 'number': 24, 'orderInMemory': 33, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3480, 'mana_cost': 9},
    'Lich': {'DolphinAddress': '80258c4e', 'element': 'Earth', 'hexCode': '23', 'isKeyCard': 0, 'isShopCard': 1, 'number': 25, 'orderInMemory': 34, 'rarity': 6, 'type': 'Weapon', 'hasCombo': 1, 'price': 2100, 'mana_cost': 5},
    'Carbuncle': {'DolphinAddress': '80258c62', 'element': 'Earth', 'hexCode': '24', 'isKeyCard': 0, 'isShopCard': 1, 'number': 26, 'orderInMemory': 35, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 450, 'mana_cost': 4},
    'Flayer Spawn': {'DolphinAddress': '80258c8a', 'element': 'Fire', 'hexCode': '26', 'isKeyCard': 0, 'isShopCard': 1, 'number': 27, 'orderInMemory': 37, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 0, 'price': 100, 'mana_cost': 1},
    'Golden Goose': {'DolphinAddress': '802589e2', 'element': 'Neutral', 'hexCode': '04', 'isKeyCard': 0, 'isShopCard': 1, 'number': 28, 'orderInMemory': 3, 'rarity': 6, 'type': 'Helper', 'hasCombo': 0, 'price': 4500, 'mana_cost': 4},
    'Zombie Dragon': {'DolphinAddress': '80258cb2', 'element': 'Earth', 'hexCode': '28', 'isKeyCard': 0, 'isShopCard': 1, 'number': 29, 'orderInMemory': 39, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 2400, 'mana_cost': 8},
    'Fire Golem': {'DolphinAddress': '80258cc6', 'element': 'Fire', 'hexCode': '29', 'isKeyCard': 0, 'isShopCard': 1, 'number': 30, 'orderInMemory': 40, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 570, 'mana_cost': 5},
    'Running Bird': {'DolphinAddress': '80258cda', 'element': 'Earth', 'hexCode': '2A', 'isKeyCard': 0, 'isShopCard': 1, 'number': 31, 'orderInMemory': 41, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 240, 'mana_cost': 5},
    'Giant Crab': {'DolphinAddress': '80258cee', 'element': 'Water', 'hexCode': '2b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 32, 'orderInMemory': 42, 'rarity': 1, 'type': 'Summons', 'hasCombo': 0, 'price': 120, 'mana_cost': 2},
    'Banshee': {'DolphinAddress': '80258d02', 'element': 'Wood', 'hexCode': '2c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 33, 'orderInMemory': 43, 'rarity': 5, 'type': 'Weapon', 'hasCombo': 0, 'price': 300, 'mana_cost': 2},
    'Land Shark': {'DolphinAddress': '80258d16', 'element': 'Water', 'hexCode': '2D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 34, 'orderInMemory': 44, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 270, 'mana_cost': 6},
    'Berserker': {'DolphinAddress': '80258d2a', 'element': 'Fire', 'hexCode': '2e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 35, 'orderInMemory': 45, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 540, 'mana_cost': 5},
    'Flying Ray': {'DolphinAddress': '80258d3e', 'element': 'Water', 'hexCode': '2f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 36, 'orderInMemory': 46, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 30, 'mana_cost': 1},
    'Demon Hound': {'DolphinAddress': '80258d52', 'element': 'Wood', 'hexCode': '30', 'isKeyCard': 0, 'isShopCard': 1, 'number': 37, 'orderInMemory': 47, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 360, 'mana_cost': 6},
    'Behemoth': {'DolphinAddress': '80258d66', 'element': 'Earth', 'hexCode': '31', 'isKeyCard': 0, 'isShopCard': 1, 'number': 38, 'orderInMemory': 48, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3150, 'mana_cost': 9},
    'Basilisk': {'DolphinAddress': '802591b2', 'element': 'Water', 'hexCode': '68', 'isKeyCard': 0, 'isShopCard': 1, 'number': 39, 'orderInMemory': 103, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 1, 'price': 105, 'mana_cost': 3},
    'Mole Monster': {'DolphinAddress': '80258d7a', 'element': 'Neutral', 'hexCode': '32', 'isKeyCard': 0, 'isShopCard': 1, 'number': 40, 'orderInMemory': 49, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 999, 'mana_cost': 6},
    'Maelstrom': {'DolphinAddress': '80258d8e', 'element': 'Water', 'hexCode': '33', 'isKeyCard': 0, 'isShopCard': 1, 'number': 41, 'orderInMemory': 50, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 60, 'mana_cost': 1},
    'Lycanthrope': {'DolphinAddress': '80258db6', 'element': 'Wood', 'hexCode': '35', 'isKeyCard': 0, 'isShopCard': 1, 'number': 42, 'orderInMemory': 52, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 0, 'price': 375, 'mana_cost': 6},
    'Sand Beetle': {'DolphinAddress': '80258dca', 'element': 'Earth', 'hexCode': '36', 'isKeyCard': 0, 'isShopCard': 1, 'number': 43, 'orderInMemory': 53, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 420, 'mana_cost': 5},
    'Necromancer': {'DolphinAddress': '80258dde', 'element': 'Neutral', 'hexCode': '37', 'isKeyCard': 0, 'isShopCard': 1, 'number': 44, 'orderInMemory': 54, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 900, 'mana_cost': 6},
    'Great Turtle': {'DolphinAddress': '80258df2', 'element': 'Earth', 'hexCode': '38', 'isKeyCard': 0, 'isShopCard': 0, 'number': 45, 'orderInMemory': 55, 'rarity': 8, 'type': 'Independent', 'hasCombo': 1, 'price': 0, 'mana_cost': 20},
    'Gold Butterfly': {'DolphinAddress': '80258e06', 'element': 'Wood', 'hexCode': '39', 'isKeyCard': 0, 'isShopCard': 1, 'number': 46, 'orderInMemory': 56, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 180, 'mana_cost': 5},
    'Ghoul': {'DolphinAddress': '80258e1a', 'element': 'Wood', 'hexCode': '3a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 47, 'orderInMemory': 57, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 0, 'price': 75, 'mana_cost': 1},
    'Treant': {'DolphinAddress': '80258e2e', 'element': 'Wood', 'hexCode': '3b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 48, 'orderInMemory': 58, 'rarity': 3, 'type': 'Helper', 'hasCombo': 1, 'price': 240, 'mana_cost': 5},
    'Sea Monk': {'DolphinAddress': '80258e56', 'element': 'Water', 'hexCode': '3d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 49, 'orderInMemory': 60, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 1440, 'mana_cost': 10},
    'King Mandragora': {'DolphinAddress': '8025919e', 'element': 'Wood', 'hexCode': '67', 'isKeyCard': 0, 'isShopCard': 1, 'number': 50, 'orderInMemory': 102, 'rarity': 7, 'type': 'Helper', 'hasCombo': 1, 'price': 2100, 'mana_cost': 4},
    'Larval Fly': {'DolphinAddress': '802591c6', 'element': 'Water', 'hexCode': '69', 'isKeyCard': 0, 'isShopCard': 1, 'number': 51, 'orderInMemory': 104, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 180, 'mana_cost': 5},
    'Crystal Rose': {'DolphinAddress': '80258e6a', 'element': 'Water', 'hexCode': '3E', 'isKeyCard': 0, 'isShopCard': 1, 'number': 52, 'orderInMemory': 61, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 1, 'price': 270, 'mana_cost': 4},
    'Dark Raven': {'DolphinAddress': '80258e7e', 'element': 'Fire', 'hexCode': '3F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 53, 'orderInMemory': 62, 'rarity': 1, 'type': 'Weapon', 'hasCombo': 1, 'price': 15, 'mana_cost': 1},
    'Wizard': {'DolphinAddress': '80258ea6', 'element': 'Fire', 'hexCode': '41', 'isKeyCard': 0, 'isShopCard': 1, 'number': 54, 'orderInMemory': 64, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 360, 'mana_cost': 6},
    'Dragonoid': {'DolphinAddress': '80258eba', 'element': 'Earth', 'hexCode': '42', 'isKeyCard': 0, 'isShopCard': 1, 'number': 55, 'orderInMemory': 65, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 300, 'mana_cost': 3},
    'Dryad': {'DolphinAddress': '80258ece', 'element': 'Wood', 'hexCode': '43', 'isKeyCard': 0, 'isShopCard': 1, 'number': 56, 'orderInMemory': 66, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 510, 'mana_cost': 5},
    'Birdman': {'DolphinAddress': '80258ee2', 'element': 'Wood', 'hexCode': '44', 'isKeyCard': 1, 'isShopCard': 0, 'number': 57, 'orderInMemory': 67, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 5},
    "Will 'o wisp": {'DolphinAddress': '80258ef6', 'element': 'Fire', 'hexCode': '45', 'isKeyCard': 0, 'isShopCard': 1, 'number': 58, 'orderInMemory': 68, 'rarity': 1, 'type': 'Helper', 'hasCombo': 0, 'price': 150, 'mana_cost': 3},
    'Archer Tree': {'DolphinAddress': '80258f0a', 'element': 'Wood', 'hexCode': '46', 'isKeyCard': 0, 'isShopCard': 1, 'number': 59, 'orderInMemory': 69, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 1, 'price': 120, 'mana_cost': 3},
    'Stone Head': {'DolphinAddress': '80258f1e', 'element': 'Fire', 'hexCode': '47', 'isKeyCard': 0, 'isShopCard': 1, 'number': 60, 'orderInMemory': 70, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 630, 'mana_cost': 5},
    'Blood Bush': {'DolphinAddress': '80258f32', 'element': 'Fire', 'hexCode': '48', 'isKeyCard': 0, 'isShopCard': 1, 'number': 61, 'orderInMemory': 71, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 120, 'mana_cost': 4},
    'Efreet': {'DolphinAddress': '80258f46', 'element': 'Fire', 'hexCode': '49', 'isKeyCard': 0, 'isShopCard': 1, 'number': 62, 'orderInMemory': 72, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 840, 'mana_cost': 4},
    'Dragon Knight': {'DolphinAddress': '80258f5a', 'element': 'Water', 'hexCode': '4a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 63, 'orderInMemory': 73, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 1, 'price': 270, 'mana_cost': 3},
    'Demon Fox': {'DolphinAddress': '80258f6e', 'element': 'Fire', 'hexCode': '4b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 64, 'orderInMemory': 74, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3330, 'mana_cost': 9},
    'Juggernaut': {'DolphinAddress': '80258f82', 'element': 'Earth', 'hexCode': '4c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 65, 'orderInMemory': 75, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 720, 'mana_cost': 5},
    'Fire Gargoyle': {'DolphinAddress': '80258f96', 'element': 'Fire', 'hexCode': '4D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 66, 'orderInMemory': 76, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 600, 'mana_cost': 8},
    'Great Demon': {'DolphinAddress': '80258faa', 'element': 'Fire', 'hexCode': '4e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 67, 'orderInMemory': 77, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 0, 'price': 720, 'mana_cost': 4},
    'Evil Eye': {'DolphinAddress': '80258fbe', 'element': 'Wood', 'hexCode': '4F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 68, 'orderInMemory': 78, 'rarity': 1, 'type': 'Helper', 'hasCombo': 0, 'price': 240, 'mana_cost': 5},
    'Blue Dragon': {'DolphinAddress': '80258fd2', 'element': 'Water', 'hexCode': '50', 'isKeyCard': 0, 'isShopCard': 0, 'number': 69, 'orderInMemory': 79, 'rarity': 8, 'type': 'Summons', 'hasCombo': 1, 'price': 0, 'mana_cost': 20},
    'Gnome': {'DolphinAddress': '80258fe6', 'element': 'Earth', 'hexCode': '51', 'isKeyCard': 0, 'isShopCard': 1, 'number': 70, 'orderInMemory': 80, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 480, 'mana_cost': 5},
    'Venom Lizard': {'DolphinAddress': '802592b6', 'element': 'Wood', 'hexCode': '75', 'isKeyCard': 0, 'isShopCard': 1, 'number': 71, 'orderInMemory': 116, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 1, 'price': 120, 'mana_cost': 2},
    'Tiger Mage': {'DolphinAddress': '80258ffa', 'element': 'Fire', 'hexCode': '52', 'isKeyCard': 0, 'isShopCard': 1, 'number': 72, 'orderInMemory': 81, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1800, 'mana_cost': 6},
    'Hydra': {'DolphinAddress': '8025900e', 'element': 'Water', 'hexCode': '53', 'isKeyCard': 0, 'isShopCard': 1, 'number': 73, 'orderInMemory': 82, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 1500, 'mana_cost': 11},
    'Siren': {'DolphinAddress': '80259022', 'element': 'Wood', 'hexCode': '54', 'isKeyCard': 0, 'isShopCard': 1, 'number': 74, 'orderInMemory': 83, 'rarity': 5, 'type': 'Independent', 'hasCombo': 1, 'price': 480, 'mana_cost': 4},
    'Salamander': {'DolphinAddress': '802592a2', 'element': 'Fire', 'hexCode': '74', 'isKeyCard': 0, 'isShopCard': 1, 'number': 75, 'orderInMemory': 115, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 510, 'mana_cost': 5},
    'Chimera': {'DolphinAddress': '80259036', 'element': 'Fire', 'hexCode': '55', 'isKeyCard': 0, 'isShopCard': 1, 'number': 76, 'orderInMemory': 84, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 690, 'mana_cost': 7},
    'Goblin Lord': {'DolphinAddress': '8025922a', 'element': 'Neutral', 'hexCode': '6e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 77, 'orderInMemory': 109, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 1140, 'mana_cost': 5},
    'Scythe Beast': {'DolphinAddress': '8025905e', 'element': 'Wood', 'hexCode': '57', 'isKeyCard': 0, 'isShopCard': 1, 'number': 78, 'orderInMemory': 86, 'rarity': 2, 'type': 'Weapon', 'hasCombo': 0, 'price': 120, 'mana_cost': 2},
    'Kitty Trap': {'DolphinAddress': '80259072', 'element': 'Fire', 'hexCode': '58', 'isKeyCard': 0, 'isShopCard': 1, 'number': 79, 'orderInMemory': 87, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 450, 'mana_cost': 5},
    'Night Mare': {'DolphinAddress': '80259086', 'element': 'Neutral', 'hexCode': '59', 'isKeyCard': 0, 'isShopCard': 1, 'number': 80, 'orderInMemory': 88, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 1800, 'mana_cost': 7},
    'Golden Phoenix': {'DolphinAddress': '8025909a', 'element': 'Fire', 'hexCode': '5a', 'isKeyCard': 0, 'isShopCard': 0, 'number': 81, 'orderInMemory': 89, 'rarity': 8, 'type': 'Helper', 'hasCombo': 1, 'price': 0, 'mana_cost': 20},
    'Rheebus': {'DolphinAddress': '8025904a', 'element': 'Wood', 'hexCode': '56', 'isKeyCard': 0, 'isShopCard': 1, 'number': 82, 'orderInMemory': 85, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 450, 'mana_cost': 5},
    'White Tiger': {'DolphinAddress': '802590ae', 'element': 'Wood', 'hexCode': '5b', 'isKeyCard': 0, 'isShopCard': 0, 'number': 83, 'orderInMemory': 90, 'rarity': 8, 'type': 'Summons', 'hasCombo': 1, 'price': 0, 'mana_cost': 20},
    'Venus Spider': {'DolphinAddress': '802590c2', 'element': 'Earth', 'hexCode': '5C', 'isKeyCard': 0, 'isShopCard': 1, 'number': 84, 'orderInMemory': 91, 'rarity': 2, 'type': 'Summons', 'hasCombo': 0, 'price': 150, 'mana_cost': 3},
    'Vampire': {'DolphinAddress': '802590d6', 'element': 'Neutral', 'hexCode': '5D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 85, 'orderInMemory': 92, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 2700, 'mana_cost': 9},
    'Sphinx': {'DolphinAddress': '802590ea', 'element': 'Earth', 'hexCode': '5E', 'isKeyCard': 0, 'isShopCard': 1, 'number': 86, 'orderInMemory': 93, 'rarity': 6, 'type': 'Weapon', 'hasCombo': 1, 'price': 1650, 'mana_cost': 10},
    'Mermaid': {'DolphinAddress': '802591da', 'element': 'Water', 'hexCode': '6a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 87, 'orderInMemory': 105, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 720, 'mana_cost': 6},
    'Puppet Master': {'DolphinAddress': '802590fe', 'element': 'Neutral', 'hexCode': '5F', 'isKeyCard': 0, 'isShopCard': 1, 'number': 88, 'orderInMemory': 94, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 1800, 'mana_cost': 7},
    'Plague Rat': {'DolphinAddress': '80259112', 'element': 'Earth', 'hexCode': '60', 'isKeyCard': 0, 'isShopCard': 1, 'number': 89, 'orderInMemory': 95, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 60, 'mana_cost': 4},
    'Undine': {'DolphinAddress': '80259126', 'element': 'Water', 'hexCode': '61', 'isKeyCard': 0, 'isShopCard': 1, 'number': 90, 'orderInMemory': 96, 'rarity': 2, 'type': 'Helper', 'hasCombo': 1, 'price': 480, 'mana_cost': 5},
    'Whip Worm': {'DolphinAddress': '8025913a', 'element': 'Wood', 'hexCode': '62', 'isKeyCard': 0, 'isShopCard': 1, 'number': 91, 'orderInMemory': 97, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 1800, 'mana_cost': 7},
    'Trickster': {'DolphinAddress': '8025914e', 'element': 'Wood', 'hexCode': '63', 'isKeyCard': 0, 'isShopCard': 1, 'number': 92, 'orderInMemory': 98, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 1350, 'mana_cost': 8},
    'Demon Skeleton': {'DolphinAddress': '802591ee', 'element': 'Water', 'hexCode': '6b', 'isKeyCard': 0, 'isShopCard': 1, 'number': 93, 'orderInMemory': 106, 'rarity': 4, 'type': 'Independent', 'hasCombo': 1, 'price': 1440, 'mana_cost': 9},
    'Caterpoker': {'DolphinAddress': '80259162', 'element': 'Wood', 'hexCode': '64', 'isKeyCard': 0, 'isShopCard': 1, 'number': 94, 'orderInMemory': 99, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 135, 'mana_cost': 4},
    'Beelzebub': {'DolphinAddress': '80259176', 'element': 'Neutral', 'hexCode': '65', 'isKeyCard': 0, 'isShopCard': 1, 'number': 95, 'orderInMemory': 100, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 1080, 'mana_cost': 9},
    'Mind Flayer': {'DolphinAddress': '80258bc2', 'element': 'Water', 'hexCode': '1c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 96, 'orderInMemory': 27, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3600, 'mana_cost': 14},
    'Ice Golem': {'DolphinAddress': '8025918a', 'element': 'Water', 'hexCode': '66', 'isKeyCard': 0, 'isShopCard': 1, 'number': 97, 'orderInMemory': 101, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3600, 'mana_cost': 9},
    'Cyclops': {'DolphinAddress': '8025923e', 'element': 'Earth', 'hexCode': '6f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 98, 'orderInMemory': 110, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 1200, 'mana_cost': 5},
    'Black Dragon': {'DolphinAddress': '80258e92', 'element': 'Neutral', 'hexCode': '40', 'isKeyCard': 0, 'isShopCard': 1, 'number': 99, 'orderInMemory': 63, 'rarity': 7, 'type': 'Independent', 'hasCombo': 0, 'price': 5700, 'mana_cost': 16},
    'Steel Skeleton': {'DolphinAddress': '80259252', 'element': 'Neutral', 'hexCode': '70', 'isKeyCard': 0, 'isShopCard': 1, 'number': 100, 'orderInMemory': 111, 'rarity': 6, 'type': 'Independent', 'hasCombo': 1, 'price': 3900, 'mana_cost': 10},
    'Chaos Knight': {'DolphinAddress': '80259266', 'element': 'Neutral', 'hexCode': '71', 'isKeyCard': 0, 'isShopCard': 1, 'number': 101, 'orderInMemory': 112, 'rarity': 5, 'type': 'Weapon', 'hasCombo': 1, 'price': 1920, 'mana_cost': 6},
    'Decoy Pillar': {'DolphinAddress': '8025927a', 'element': 'Neutral', 'hexCode': '72', 'isKeyCard': 0, 'isShopCard': 1, 'number': 102, 'orderInMemory': 113, 'rarity': 5, 'type': 'Helper', 'hasCombo': 1, 'price': 4800, 'mana_cost': 9},
    'Elephant King': {'DolphinAddress': '80258c9e', 'element': 'Earth', 'hexCode': '27', 'isKeyCard': 0, 'isShopCard': 1, 'number': 103, 'orderInMemory': 38, 'rarity': 6, 'type': 'Summons', 'hasCombo': 1, 'price': 3900, 'mana_cost': 8},
    'God of Destruction': {'DolphinAddress': '802592ca', 'element': 'Neutral', 'hexCode': '76', 'isKeyCard': 1, 'isShopCard': 0, 'number': 104, 'orderInMemory': 117, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 12},
    'Doppelganger': {'DolphinAddress': '8025928e', 'element': 'Neutral', 'hexCode': '73', 'isKeyCard': 0, 'isShopCard': 0, 'number': 105, 'orderInMemory': 114, 'rarity': 8, 'type': 'Independent', 'hasCombo': 1, 'price': 0, 'mana_cost': 10},
    'Earth Elemental': {'DolphinAddress': '802592de', 'element': 'Earth', 'hexCode': '77', 'isKeyCard': 0, 'isShopCard': 1, 'number': 106, 'orderInMemory': 118, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6},
    'Water Elemental': {'DolphinAddress': '802592f2', 'element': 'Water', 'hexCode': '78', 'isKeyCard': 0, 'isShopCard': 1, 'number': 107, 'orderInMemory': 119, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6},
    'Fire Elemental': {'DolphinAddress': '80259306', 'element': 'Fire', 'hexCode': '79', 'isKeyCard': 0, 'isShopCard': 1, 'number': 108, 'orderInMemory': 120, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6},
    'Wood Elemental': {'DolphinAddress': '8025931a', 'element': 'Wood', 'hexCode': '7a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 109, 'orderInMemory': 121, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1200, 'mana_cost': 6},
    'Aggressor GL2': {'DolphinAddress': '80259aea', 'element': 'Mech', 'hexCode': 'de', 'isKeyCard': 0, 'isShopCard': 1, 'number': 110, 'orderInMemory': 214, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 180, 'mana_cost': 5},
    'Succubus': {'DolphinAddress': '80258bd6', 'element': 'Neutral', 'hexCode': '1d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 111, 'orderInMemory': 28, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 1500, 'mana_cost': 8},
    'Incubus': {'DolphinAddress': '80258bea', 'element': 'Neutral', 'hexCode': '1e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 112, 'orderInMemory': 29, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 1500, 'mana_cost': 11},
    'Valkyrie': {'DolphinAddress': '80258a0a', 'element': 'Fire', 'hexCode': '6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 113, 'orderInMemory': 5, 'rarity': 7, 'type': 'Summons', 'hasCombo': 1, 'price': 7200, 'mana_cost': 8},
    'Napalm Beast': {'DolphinAddress': '8025954a', 'element': 'Fire', 'hexCode': '96', 'isKeyCard': 0, 'isShopCard': 1, 'number': 114, 'orderInMemory': 149, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 900, 'mana_cost': 7},
    'Green Dragon': {'DolphinAddress': '8025955e', 'element': 'Wood', 'hexCode': '97', 'isKeyCard': 0, 'isShopCard': 1, 'number': 115, 'orderInMemory': 150, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 6000, 'mana_cost': 10},
    'Wyvern': {'DolphinAddress': '802593ce', 'element': 'Neutral', 'hexCode': '83', 'isKeyCard': 0, 'isShopCard': 1, 'number': 116, 'orderInMemory': 130, 'rarity': 6, 'type': 'Transform', 'hasCombo': 0, 'price': 780, 'mana_cost': 4},
    'Sprite': {'DolphinAddress': '802598ce', 'element': 'Water', 'hexCode': 'c3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 117, 'orderInMemory': 190, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 480, 'mana_cost': 5},
    'Leprechaun': {'DolphinAddress': '8025973e', 'element': 'Fire', 'hexCode': 'af', 'isKeyCard': 0, 'isShopCard': 1, 'number': 118, 'orderInMemory': 174, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 300, 'mana_cost': 6},
    'Charadrius': {'DolphinAddress': '80259716', 'element': 'Water', 'hexCode': 'ad', 'isKeyCard': 0, 'isShopCard': 1, 'number': 119, 'orderInMemory': 172, 'rarity': 5, 'type': 'Weapon', 'hasCombo': 0, 'price': 450, 'mana_cost': 4},
    'Yowie': {'DolphinAddress': '80259392', 'element': 'Water', 'hexCode': '80', 'isKeyCard': 0, 'isShopCard': 1, 'number': 120, 'orderInMemory': 127, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 0},
    'Apsaras': {'DolphinAddress': '80259a22', 'element': 'Water', 'hexCode': 'd4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 121, 'orderInMemory': 205, 'rarity': 6, 'type': 'Helper', 'hasCombo': 0, 'price': 2100, 'mana_cost': 9},
    'Death': {'DolphinAddress': '802594d2', 'element': 'Neutral', 'hexCode': '90', 'isKeyCard': 0, 'isShopCard': 1, 'number': 122, 'orderInMemory': 143, 'rarity': 3, 'type': 'Weapon', 'hasCombo': 0, 'price': 540, 'mana_cost': 4},
    'Porcupig': {'DolphinAddress': '802595c2', 'element': 'Earth', 'hexCode': '9c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 123, 'orderInMemory': 155, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 1},
    'Golden Porcupig': {'DolphinAddress': '802595d6', 'element': 'Earth', 'hexCode': '9d', 'isKeyCard': 0, 'isShopCard': 1, 'number': 124, 'orderInMemory': 156, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 45, 'mana_cost': 2},
    'Mandra Dancer': {'DolphinAddress': '802599aa', 'element': 'Wood', 'hexCode': 'ce', 'isKeyCard': 0, 'isShopCard': 1, 'number': 125, 'orderInMemory': 200, 'rarity': 4, 'type': 'Independent', 'hasCombo': 1, 'price': 270, 'mana_cost': 3},
    'Super Pumper': {'DolphinAddress': '8025990a', 'element': 'Water', 'hexCode': 'c6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 126, 'orderInMemory': 193, 'rarity': 7, 'type': 'Helper', 'hasCombo': 0, 'price': 2700, 'mana_cost': 5},
    'Lucky Lion': {'DolphinAddress': '802597b6', 'element': 'Fire', 'hexCode': 'B5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 127, 'orderInMemory': 180, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 1350, 'mana_cost': 8},
    'Vodianoi': {'DolphinAddress': '802597ca', 'element': 'Water', 'hexCode': 'b6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 128, 'orderInMemory': 181, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 450, 'mana_cost': 9},
    'Uroboros': {'DolphinAddress': '802597de', 'element': 'Earth', 'hexCode': 'b7', 'isKeyCard': 0, 'isShopCard': 0, 'number': 129, 'orderInMemory': 182, 'rarity': 8, 'type': 'Helper', 'hasCombo': 0, 'price': 0, 'mana_cost': 6},
    'Yin Yang': {'DolphinAddress': '80259842', 'element': 'Neutral', 'hexCode': 'bc', 'isKeyCard': 0, 'isShopCard': 1, 'number': 130, 'orderInMemory': 184, 'rarity': 7, 'type': 'Independent', 'hasCombo': 0, 'price': 2700, 'mana_cost': 6},
    'Dao': {'DolphinAddress': '80259446', 'element': 'Earth', 'hexCode': '89', 'isKeyCard': 0, 'isShopCard': 1, 'number': 131, 'orderInMemory': 136, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 840, 'mana_cost': 4},
    'Manticore': {'DolphinAddress': '8025945a', 'element': 'Fire', 'hexCode': '8a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 132, 'orderInMemory': 137, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 960, 'mana_cost': 7},
    'March Hare': {'DolphinAddress': '8025950e', 'element': 'Water', 'hexCode': '93', 'isKeyCard': 0, 'isShopCard': 1, 'number': 133, 'orderInMemory': 146, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 1200, 'mana_cost': 6},
    'Marid': {'DolphinAddress': '802594aa', 'element': 'Water', 'hexCode': '8E', 'isKeyCard': 0, 'isShopCard': 1, 'number': 134, 'orderInMemory': 141, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 510, 'mana_cost': 4},
    'Elf': {'DolphinAddress': '80259356', 'element': 'Wood', 'hexCode': '7D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 135, 'orderInMemory': 124, 'rarity': 3, 'type': 'Independent', 'hasCombo': 1, 'price': 450, 'mana_cost': 6},
    'Elf Lord': {'DolphinAddress': '8025936a', 'element': 'Wood', 'hexCode': '7e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 136, 'orderInMemory': 125, 'rarity': 6, 'type': 'Independent', 'hasCombo': 1, 'price': 990, 'mana_cost': 8},
    'Dark Elf': {'DolphinAddress': '80259482', 'element': 'Neutral', 'hexCode': '8c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 137, 'orderInMemory': 139, 'rarity': 5, 'type': 'Independent', 'hasCombo': 1, 'price': 1200, 'mana_cost': 7},
    'Global Bust': {'DolphinAddress': '802596da', 'element': 'Earth', 'hexCode': 'aa', 'isKeyCard': 0, 'isShopCard': 1, 'number': 138, 'orderInMemory': 169, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 630, 'mana_cost': 8},
    'Garuda': {'DolphinAddress': '80258da2', 'element': 'Wood', 'hexCode': '34', 'isKeyCard': 0, 'isShopCard': 1, 'number': 139, 'orderInMemory': 51, 'rarity': 7, 'type': 'Transform', 'hasCombo': 0, 'price': 2100, 'mana_cost': 10},
    'Popgun Charlie': {'DolphinAddress': '8025987e', 'element': 'Fire', 'hexCode': 'bf', 'isKeyCard': 0, 'isShopCard': 1, 'number': 140, 'orderInMemory': 187, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 60, 'mana_cost': 2},
    'Acid Cloud': {'DolphinAddress': '8025941e', 'element': 'Earth', 'hexCode': '87', 'isKeyCard': 0, 'isShopCard': 1, 'number': 141, 'orderInMemory': 134, 'rarity': 4, 'type': 'Independent', 'hasCombo': 1, 'price': 450, 'mana_cost': 2},
    'Baby Dragon': {'DolphinAddress': '80259342', 'element': 'Earth', 'hexCode': '7c', 'isKeyCard': 0, 'isShopCard': 1, 'number': 142, 'orderInMemory': 123, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 120, 'mana_cost': 2},
    'Brine Dragon': {'DolphinAddress': '802594fa', 'element': 'Water', 'hexCode': '92', 'isKeyCard': 0, 'isShopCard': 1, 'number': 143, 'orderInMemory': 145, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 6300, 'mana_cost': 10},
    'Circasaurus': {'DolphinAddress': '80259a36', 'element': 'Wood', 'hexCode': 'd5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 144, 'orderInMemory': 206, 'rarity': 1, 'type': 'Transform', 'hasCombo': 0, 'price': 300, 'mana_cost': 3},
    'Stone Golem': {'DolphinAddress': '80259a5e', 'element': 'Earth', 'hexCode': 'D7', 'isKeyCard': 1, 'isShopCard': 0, 'number': 145, 'orderInMemory': 208, 'rarity': 4, 'type': 'Transform', 'hasCombo': 1, 'price': 0, 'mana_cost': 8},
    'Gizmolizer': {'DolphinAddress': '80259aae', 'element': 'Mech', 'hexCode': 'DB', 'isKeyCard': 0, 'isShopCard': 1, 'number': 146, 'orderInMemory': 212, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 840, 'mana_cost': 5},
    'MechLance 5L': {'DolphinAddress': '80259b3a', 'element': 'Mech', 'hexCode': 'e2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 147, 'orderInMemory': 218, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 150, 'mana_cost': 2},
    'Fireworks': {'DolphinAddress': '8025968a', 'element': 'Fire', 'hexCode': 'a6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 148, 'orderInMemory': 165, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 720, 'mana_cost': 9},
    'Sekmet': {'DolphinAddress': '80259946', 'element': 'Wood', 'hexCode': 'C9', 'isKeyCard': 0, 'isShopCard': 0, 'number': 149, 'orderInMemory': 196, 'rarity': 8, 'type': 'Weapon', 'hasCombo': 1, 'price': 0, 'mana_cost': 10},
    'Undead Knight': {'DolphinAddress': '8025991e', 'element': 'Fire', 'hexCode': 'c7', 'isKeyCard': 0, 'isShopCard': 1, 'number': 150, 'orderInMemory': 194, 'rarity': 2, 'type': 'Independent', 'hasCombo': 0, 'price': 120, 'mana_cost': 2},
    'Panther Mage': {'DolphinAddress': '80259932', 'element': 'Wood', 'hexCode': 'c8', 'isKeyCard': 0, 'isShopCard': 1, 'number': 151, 'orderInMemory': 195, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 1800, 'mana_cost': 8},
    'Lamassu': {'DolphinAddress': '802593ba', 'element': 'Earth', 'hexCode': '82', 'isKeyCard': 0, 'isShopCard': 1, 'number': 152, 'orderInMemory': 129, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 480, 'mana_cost': 5},
    'LazerBug 39K': {'DolphinAddress': '80259b76', 'element': 'Mech', 'hexCode': 'e5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 153, 'orderInMemory': 221, 'rarity': 6, 'type': 'Summons', 'hasCombo': 0, 'price': 2100, 'mana_cost': 11},
    'Myconid': {'DolphinAddress': '8025977a', 'element': 'Earth', 'hexCode': 'b2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 154, 'orderInMemory': 177, 'rarity': 2, 'type': 'Helper', 'hasCombo': 0, 'price': 72, 'mana_cost': 1},
    'Spartoi': {'DolphinAddress': '802597a2', 'element': 'Earth', 'hexCode': 'B4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 155, 'orderInMemory': 179, 'rarity': 6, 'type': 'Weapon', 'hasCombo': 0, 'price': 1800, 'mana_cost': 4},
    'Phantom Ship': {'DolphinAddress': '802599fa', 'element': 'Water', 'hexCode': 'd2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 156, 'orderInMemory': 203, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 7500, 'mana_cost': 13},
    'Raflesia': {'DolphinAddress': '802598a6', 'element': 'Wood', 'hexCode': 'C1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 157, 'orderInMemory': 189, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 240, 'mana_cost': 3},
    'Daidarapochi': {'DolphinAddress': '80259586', 'element': 'Water', 'hexCode': '99', 'isKeyCard': 0, 'isShopCard': 1, 'number': 158, 'orderInMemory': 152, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 4500, 'mana_cost': 14},
    'Gemini': {'DolphinAddress': '8025963a', 'element': 'Fire', 'hexCode': 'A2', 'isKeyCard': 0, 'isShopCard': 1, 'number': 159, 'orderInMemory': 161, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 4200, 'mana_cost': 12},
    'Amber Dragon': {'DolphinAddress': '802595ae', 'element': 'Earth', 'hexCode': '9B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 160, 'orderInMemory': 154, 'rarity': 5, 'type': 'Summons', 'hasCombo': 1, 'price': 6000, 'mana_cost': 10},
    'Demon Lord': {'DolphinAddress': '80259806', 'element': 'Fire', 'hexCode': 'b9', 'isKeyCard': 0, 'isShopCard': 1, 'number': 161, 'orderInMemory': 183, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 1440, 'mana_cost': 9},
    'Witchlette': {'DolphinAddress': '80259a0e', 'element': 'Water', 'hexCode': 'D3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 162, 'orderInMemory': 204, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 120, 'mana_cost': 1},
    'AcidBot': {'DolphinAddress': '80259b9e', 'element': 'Mech', 'hexCode': 'E7', 'isKeyCard': 0, 'isShopCard': 1, 'number': 163, 'orderInMemory': 223, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 150, 'mana_cost': 3},
    'Chameleus': {'DolphinAddress': '80258c76', 'element': 'Wood', 'hexCode': '25', 'isKeyCard': 0, 'isShopCard': 1, 'number': 164, 'orderInMemory': 36, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 3000, 'mana_cost': 6},
    'Devil Plant': {'DolphinAddress': '80258ae6', 'element': 'Wood', 'hexCode': '11', 'isKeyCard': 0, 'isShopCard': 1, 'number': 165, 'orderInMemory': 16, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 840, 'mana_cost': 8},
    'Centaur': {'DolphinAddress': '80258aaa', 'element': 'Wood', 'hexCode': '0e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 166, 'orderInMemory': 13, 'rarity': 6, 'type': 'Transform', 'hasCombo': 0, 'price': 4200, 'mana_cost': 6},
    'Dark Treant': {'DolphinAddress': '80259612', 'element': 'Wood', 'hexCode': 'A0', 'isKeyCard': 0, 'isShopCard': 1, 'number': 167, 'orderInMemory': 159, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 840, 'mana_cost': 5},
    'Coal Treant': {'DolphinAddress': '8025964e', 'element': 'Fire', 'hexCode': 'A3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 168, 'orderInMemory': 162, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 600, 'mana_cost': 5},
    'Sleeping Giant': {'DolphinAddress': '80259676', 'element': 'Wood', 'hexCode': 'a5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 169, 'orderInMemory': 164, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 540, 'mana_cost': 6},
    'Gravity Pillar': {'DolphinAddress': '802596ee', 'element': 'Neutral', 'hexCode': 'AB', 'isKeyCard': 0, 'isShopCard': 1, 'number': 170, 'orderInMemory': 170, 'rarity': 7, 'type': 'Helper', 'hasCombo': 1, 'price': 4800, 'mana_cost': 7},
    'Storm Hagan': {'DolphinAddress': '8025969e', 'element': 'Wood', 'hexCode': 'a7', 'isKeyCard': 0, 'isShopCard': 1, 'number': 171, 'orderInMemory': 166, 'rarity': 2, 'type': 'Summons', 'hasCombo': 1, 'price': 240, 'mana_cost': 4},
    'Rock Hagan': {'DolphinAddress': '802596b2', 'element': 'Water', 'hexCode': 'A8', 'isKeyCard': 0, 'isShopCard': 1, 'number': 172, 'orderInMemory': 167, 'rarity': 2, 'type': 'Summons', 'hasCombo': 1, 'price': 240, 'mana_cost': 4},
    'Bum Hagan': {'DolphinAddress': '802596c6', 'element': 'Earth', 'hexCode': 'A9', 'isKeyCard': 0, 'isShopCard': 1, 'number': 173, 'orderInMemory': 168, 'rarity': 2, 'type': 'Summons', 'hasCombo': 1, 'price': 240, 'mana_cost': 4},
    'Octobush': {'DolphinAddress': '80259996', 'element': 'Neutral', 'hexCode': 'cd', 'isKeyCard': 0, 'isShopCard': 1, 'number': 174, 'orderInMemory': 199, 'rarity': 7, 'type': 'Helper', 'hasCombo': 0, 'price': 1500, 'mana_cost': 9},
    'Chariobot': {'DolphinAddress': '802599e6', 'element': 'Mech', 'hexCode': 'd1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 175, 'orderInMemory': 202, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 750, 'mana_cost': 6},
    'Dark Sprite': {'DolphinAddress': '802598f6', 'element': 'Neutral', 'hexCode': 'c5', 'isKeyCard': 0, 'isShopCard': 1, 'number': 176, 'orderInMemory': 192, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 480, 'mana_cost': 5},
    'Gargoyle': {'DolphinAddress': '8025995a', 'element': 'Fire', 'hexCode': 'ca', 'isKeyCard': 0, 'isShopCard': 1, 'number': 177, 'orderInMemory': 197, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 390, 'mana_cost': 2},
    'MechaPult': {'DolphinAddress': '80259b12', 'element': 'Mech', 'hexCode': 'E0', 'isKeyCard': 0, 'isShopCard': 1, 'number': 178, 'orderInMemory': 216, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 480, 'mana_cost': 4},
    'Aggressor DX5': {'DolphinAddress': '80259b26', 'element': 'Mech', 'hexCode': 'e1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 179, 'orderInMemory': 217, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 600, 'mana_cost': 8},
    'Matador': {'DolphinAddress': '80259662', 'element': 'Fire', 'hexCode': 'a4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 180, 'orderInMemory': 163, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 630, 'mana_cost': 5},
    'Phooka': {'DolphinAddress': '80259626', 'element': 'Water', 'hexCode': 'a1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 181, 'orderInMemory': 160, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 1200, 'mana_cost': 5},
    'Devata': {'DolphinAddress': '802594e6', 'element': 'Neutral', 'hexCode': '91', 'isKeyCard': 0, 'isShopCard': 1, 'number': 182, 'orderInMemory': 144, 'rarity': 4, 'type': 'Transform', 'hasCombo': 0, 'price': 1200, 'mana_cost': 6},
    'Barometz': {'DolphinAddress': '80258b9a', 'element': 'Earth', 'hexCode': '1a', 'isKeyCard': 0, 'isShopCard': 1, 'number': 183, 'orderInMemory': 25, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 600, 'mana_cost': 4},
    'Cerberus': {'DolphinAddress': '80258a32', 'element': 'Fire', 'hexCode': '08', 'isKeyCard': 0, 'isShopCard': 1, 'number': 184, 'orderInMemory': 7, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 1500, 'mana_cost': 5},
    'Thanatos': {'DolphinAddress': '80258a1e', 'element': 'Neutral', 'hexCode': '07', 'isKeyCard': 0, 'isShopCard': 1, 'number': 185, 'orderInMemory': 6, 'rarity': 7, 'type': 'Summons', 'hasCombo': 1, 'price': 6000, 'mana_cost': 12},
    'Nueh': {'DolphinAddress': '80258e42', 'element': 'Wood', 'hexCode': '3C', 'isKeyCard': 0, 'isShopCard': 1, 'number': 186, 'orderInMemory': 59, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 1950, 'mana_cost': 13},
    'Horus': {'DolphinAddress': '802599be', 'element': 'Wood', 'hexCode': 'cf', 'isKeyCard': 0, 'isShopCard': 1, 'number': 187, 'orderInMemory': 201, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 750, 'mana_cost': 4},
    'Acid Dragon': {'DolphinAddress': '802598e2', 'element': 'Neutral', 'hexCode': 'C4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 188, 'orderInMemory': 191, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 5400, 'mana_cost': 11},
    'Rubber Froggy': {'DolphinAddress': '8025986a', 'element': 'Water', 'hexCode': 'be', 'isKeyCard': 0, 'isShopCard': 1, 'number': 189, 'orderInMemory': 186, 'rarity': 3, 'type': 'Independent', 'hasCombo': 0, 'price': 330, 'mana_cost': 6},
    'Boom Monkey': {'DolphinAddress': '80259856', 'element': 'Fire', 'hexCode': 'BD', 'isKeyCard': 0, 'isShopCard': 1, 'number': 190, 'orderInMemory': 185, 'rarity': 6, 'type': 'Independent', 'hasCombo': 0, 'price': 1200, 'mana_cost': 2},
    'UberBomberBot': {'DolphinAddress': '80259ad6', 'element': 'Mech', 'hexCode': 'DD', 'isKeyCard': 0, 'isShopCard': 1, 'number': 191, 'orderInMemory': 213, 'rarity': 4, 'type': 'Independent', 'hasCombo': 0, 'price': 600, 'mana_cost': 5},
    'Gorgon': {'DolphinAddress': '80259496', 'element': 'Neutral', 'hexCode': '8D', 'isKeyCard': 0, 'isShopCard': 1, 'number': 192, 'orderInMemory': 140, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 810, 'mana_cost': 8},
    'Pixie': {'DolphinAddress': '80259432', 'element': 'Earth', 'hexCode': '88', 'isKeyCard': 0, 'isShopCard': 1, 'number': 193, 'orderInMemory': 135, 'rarity': 3, 'type': 'Independent', 'hasCombo': 1, 'price': 360, 'mana_cost': 4},
    'Baba Yaga': {'DolphinAddress': '802593f6', 'element': 'Water', 'hexCode': '85', 'isKeyCard': 0, 'isShopCard': 1, 'number': 194, 'orderInMemory': 132, 'rarity': 5, 'type': 'Transform', 'hasCombo': 0, 'price': 1110, 'mana_cost': 9},
    'Berserk Master': {'DolphinAddress': '8025940a', 'element': 'Fire', 'hexCode': '86', 'isKeyCard': 0, 'isShopCard': 1, 'number': 195, 'orderInMemory': 133, 'rarity': 7, 'type': 'Independent', 'hasCombo': 0, 'price': 2100, 'mana_cost': 5},
    'Rabandos': {'DolphinAddress': '802593e2', 'element': 'Neutral', 'hexCode': '84', 'isKeyCard': 0, 'isShopCard': 0, 'number': 196, 'orderInMemory': 131, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 13},
    'Hell Hound': {'DolphinAddress': '802593a6', 'element': 'Fire', 'hexCode': '81', 'isKeyCard': 1, 'isShopCard': 0, 'number': 197, 'orderInMemory': 128, 'rarity': 3, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 7},
    'Tumble Chick': {'DolphinAddress': '80259752', 'element': 'Earth', 'hexCode': 'b0', 'isKeyCard': 0, 'isShopCard': 1, 'number': 198, 'orderInMemory': 175, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 15, 'mana_cost': 1},
    'Mad Reverser': {'DolphinAddress': '80259766', 'element': 'Wood', 'hexCode': 'b1', 'isKeyCard': 0, 'isShopCard': 1, 'number': 199, 'orderInMemory': 176, 'rarity': 6, 'type': 'Helper', 'hasCombo': 0, 'price': 900, 'mana_cost': 6},
    'Sleipnir': {'DolphinAddress': '8025978e', 'element': 'Water', 'hexCode': 'b3', 'isKeyCard': 0, 'isShopCard': 0, 'number': 200, 'orderInMemory': 178, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 15},
    'Claws-R-Us': {'DolphinAddress': '80259b4e', 'element': 'Mech', 'hexCode': 'e3', 'isKeyCard': 0, 'isShopCard': 1, 'number': 201, 'orderInMemory': 219, 'rarity': 5, 'type': 'Independent', 'hasCombo': 0, 'price': 900, 'mana_cost': 10},
    'TriBlaster': {'DolphinAddress': '80259b62', 'element': 'Mech', 'hexCode': 'e4', 'isKeyCard': 0, 'isShopCard': 1, 'number': 202, 'orderInMemory': 220, 'rarity': 5, 'type': 'Summons', 'hasCombo': 0, 'price': 1200, 'mana_cost': 11},
    'Anarchy Owl': {'DolphinAddress': '80259a4a', 'element': 'Wood', 'hexCode': 'd6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 203, 'orderInMemory': 207, 'rarity': 3, 'type': 'Helper', 'hasCombo': 0, 'price': 900, 'mana_cost': 5},
    'Pegasus': {'DolphinAddress': '80259982', 'element': 'Wood', 'hexCode': 'cc', 'isKeyCard': 0, 'isShopCard': 0, 'number': 204, 'orderInMemory': 198, 'rarity': 7, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 10},
    'Phoenix': {'DolphinAddress': '80258a46', 'element': 'Fire', 'hexCode': '09', 'isKeyCard': 0, 'isShopCard': 1, 'number': 205, 'orderInMemory': 8, 'rarity': 6, 'type': 'Helper', 'hasCombo': 1, 'price': 2400, 'mana_cost': 12},
    'Ashura': {'DolphinAddress': '80258b0e', 'element': 'Fire', 'hexCode': '13', 'isKeyCard': 0, 'isShopCard': 1, 'number': 206, 'orderInMemory': 18, 'rarity': 8, 'type': 'Helper', 'hasCombo': 0, 'price': 9999, 'mana_cost': 10},
    'Talos': {'DolphinAddress': '80259702', 'element': 'Earth', 'hexCode': 'ac', 'isKeyCard': 0, 'isShopCard': 0, 'number': 207, 'orderInMemory': 171, 'rarity': 7, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 7},
    'Crystal Magic': {'DolphinAddress': '8025972a', 'element': 'Neutral', 'hexCode': 'ae', 'isKeyCard': 0, 'isShopCard': 0, 'number': 208, 'orderInMemory': 173, 'rarity': 5, 'type': 'Helper', 'hasCombo': 0, 'price': 0, 'mana_cost': 16},
    'Psycho Dice': {'DolphinAddress': '802595fe', 'element': 'Neutral', 'hexCode': '9f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 209, 'orderInMemory': 158, 'rarity': 4, 'type': 'Summons', 'hasCombo': 0, 'price': 3600, 'mana_cost': 6},
    'Blue Mold': {'DolphinAddress': '80259572', 'element': 'Earth', 'hexCode': '98', 'isKeyCard': 0, 'isShopCard': 1, 'number': 210, 'orderInMemory': 151, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 510, 'mana_cost': 9},
    'Jade Giant': {'DolphinAddress': '8025946e', 'element': 'Fire', 'hexCode': '8B', 'isKeyCard': 0, 'isShopCard': 1, 'number': 211, 'orderInMemory': 138, 'rarity': 3, 'type': 'Summons', 'hasCombo': 0, 'price': 360, 'mana_cost': 5},
    'Fafnir': {'DolphinAddress': '8025932e', 'element': 'Fire', 'hexCode': '7b', 'isKeyCard': 0, 'isShopCard': 0, 'number': 212, 'orderInMemory': 122, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 16},
    'Beaker': {'DolphinAddress': '8025937e', 'element': 'Water', 'hexCode': '7f', 'isKeyCard': 0, 'isShopCard': 1, 'number': 213, 'orderInMemory': 126, 'rarity': 1, 'type': 'Independent', 'hasCombo': 0, 'price': 24, 'mana_cost': 1},
    'Pazuzu': {'DolphinAddress': '80259536', 'element': 'Earth', 'hexCode': '95', 'isKeyCard': 0, 'isShopCard': 0, 'number': 214, 'orderInMemory': 148, 'rarity': 8, 'type': 'Transform', 'hasCombo': 0, 'price': 0, 'mana_cost': 13},
    'Super Scrubber': {'DolphinAddress': '80259afe', 'element': 'Mech', 'hexCode': 'DF', 'isKeyCard': 0, 'isShopCard': 1, 'number': 215, 'orderInMemory': 215, 'rarity': 4, 'type': 'Helper', 'hasCombo': 0, 'price': 360, 'mana_cost': 2},
    'AstroBot': {'DolphinAddress': '80259b8a', 'element': 'Mech', 'hexCode': 'E6', 'isKeyCard': 0, 'isShopCard': 1, 'number': 216, 'orderInMemory': 222, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 3600, 'mana_cost': 10},
    'Vouivre': {'DolphinAddress': '802595ea', 'element': 'Earth', 'hexCode': '9e', 'isKeyCard': 0, 'isShopCard': 1, 'number': 217, 'orderInMemory': 157, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 5400, 'mana_cost': 5},
    'Fire Moray': {'DolphinAddress': '80259a72', 'element': 'Fire', 'hexCode': 'd8', 'isKeyCard': 0, 'isShopCard': 1, 'number': 218, 'orderInMemory': 209, 'rarity': 4, 'type': 'Helper', 'hasCombo': 1, 'price': 480, 'mana_cost': 3},
    'Water Moray': {'DolphinAddress': '80259a86', 'element': 'Water', 'hexCode': 'D9', 'isKeyCard': 0, 'isShopCard': 1, 'number': 219, 'orderInMemory': 210, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 480, 'mana_cost': 3},
    'Earth Moray': {'DolphinAddress': '80259a9a', 'element': 'Earth', 'hexCode': 'DA', 'isKeyCard': 0, 'isShopCard': 1, 'number': 220, 'orderInMemory': 211, 'rarity': 4, 'type': 'Weapon', 'hasCombo': 1, 'price': 480, 'mana_cost': 3},
    'Ryuhi': {'DolphinAddress': '80259522', 'element': 'Wood', 'hexCode': '94', 'isKeyCard': 0, 'isShopCard': 0, 'number': 221, 'orderInMemory': 147, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 16},
    'Demon Swordsman': {'DolphinAddress': '8025959a', 'element': 'Earth', 'hexCode': '9A', 'isKeyCard': 0, 'isShopCard': 0, 'number': 222, 'orderInMemory': 153, 'rarity': 7, 'type': 'Weapon', 'hasCombo': 0, 'price': 0, 'mana_cost': 10},
    'Ice Skeleton': {'DolphinAddress': '80259892', 'element': 'Water', 'hexCode': 'C0', 'isKeyCard': 0, 'isShopCard': 0, 'number': 223, 'orderInMemory': 188, 'rarity': 8, 'type': 'Independent', 'hasCombo': 1, 'price': 0, 'mana_cost': 18},
    'Sacred Umpire': {'DolphinAddress': '80259bb2', 'element': 'Mech', 'hexCode': 'E8', 'isKeyCard': 0, 'isShopCard': 0, 'number': 224, 'orderInMemory': 224, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 12},
    'Emperor': {'DolphinAddress': '802594be', 'element': 'Neutral', 'hexCode': '8f', 'isKeyCard': 0, 'isShopCard': 0, 'number': 225, 'orderInMemory': 142, 'rarity': 8, 'type': 'Summons', 'hasCombo': 0, 'price': 0, 'mana_cost': 10},
}

lostkingdoms_2_custom_prices = {
    "Jack-O-Lantern": {"price": 1000},
    "Great Turtle": {"price": 8000},
    "Birdman": {"price": 1500},
    "Blue Dragon": {"price": 8000},
    "Golden Phoenix": {"price": 8000},
    "White Tiger": {"price": 8000},
    "God of Destruction": {"price": 9999},
    "Doppelganger": {"price": 9999},
    "Fafnir": {"price": 6000},
    "Hell Hound": {"price": 1200},
    "Rabandos": {"price": 3500},
    "Uroboros": {"price": 4500},
    "Sekmet": {"price": 3000},
    "Stone Golem": {"price": 2000},
    "Talos": {"price": 3000},
    "Crystal Magic": {"price": 3000},
    "Pegasus": {"price": 2500},
    "Ryuhi": {"price": 3000},
    "Demon Swordsman": {"price": 2000},
    "Ice Skeleton": {"price": 5000},
    "Sacred Umpire": {"price": 5000},
    "Emperor": {"price": 7000},
    "Sleipnir": {"price": 3500},
    "Pazuzu": {"price": 4000},
}

lost_kingdoms_2_flying_cards = ["Baba Yaga", "Birdman", "Garuda", "Wyvern", "Pazuzu"]
lost_kingdoms_2_jumping_cards = ["Hell Hound", "Cerberus", "Centaur"]
#lost_kingdoms_2_smashing_cards = ["Stone Golem", "Baba Yaga", "Talos", "CircaSaurus", "Devata", "Pazuzu", "Chariobot"]
#lost_kingdoms_2_stationary_cards = ["Dark Treant", "King Mandragora", "Rheebus", "Fairy", "Treant", "Gravity Pillar",
#                                    "Coal Treant", "Vampire Bush", "Mandragora", "Decoy Pillar", "Maelstrom", "Siren",
#                                    "MechaPult","Catoblepas","Myconid","Wood Elemental","Fire Elemental","Water Elemental",
#                                    "Kitty Trap", "Will 'o wisp", "Great Turtle", "Global Bust", "Super Pumper",
#                                    "AcidBot", "Claws-R-Us", "Earth Elemental", "Fire Moray", "Water Moray", "Earth Moray"]

#Adds 176 cards randomly to the pool, matching the amount of chest locations in the game.
for key in lost_kingdoms_2_cards:
    lost_kingdoms_2_items[key] = {}
    lost_kingdoms_2_items[key]["Type"] = "Card"
    lost_kingdoms_2_items[key]["Amount"] = 1
    lost_kingdoms_2_items[key]["id"] = lost_kingdoms_2_cards[key]["number"]

key_item_id = 1000
for key in lost_kingdoms_2_key_items:
    lost_kingdoms_2_items[key] = {}
    lost_kingdoms_2_items[key]["Type"] = "Key Item"
    lost_kingdoms_2_items[key]["Amount"] = 1
    lost_kingdoms_2_items[key]["id"] = key_item_id
    key_item_id+=1

lost_kingdoms_2_items["Magic Boosters"] = {"Type": "Magic Boosters", "Amount": 1, "id": 2000}
lost_kingdoms_2_items["Red Fairy"] = {"Type": "Red Fairy", "Amount": 100, "id": 3000}
lost_kingdoms_2_items["Progressive Player Level"] = {"Type": "Progressive Player Level", "Amount": 19, "id": 4000}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Fire"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "id": 5000}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Water"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "id": 5001}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Earth"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "id": 5002}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Wood"] = {"Type": "Progressive Attribute Proficiency", "Amount": 5, "id": 5003}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Neutral"] = {"Type": "Progressive Attribute Proficiency", "Amount": 7, "id": 5004}
lost_kingdoms_2_items["Progressive Attribute Proficiency: Mech"] = {"Type": "Progressive Attribute Proficiency", "Amount": 7, "id": 5005}