from typing import NamedTuple, Optional, List
from BaseClasses import Location, Region

class LK2LocationData(NamedTuple):
    iso_address: str
    missable: bool
    ram_address: str
    bit_offset: int
    id: int

class LK2Location(Location):
    game = "Lost Kingdoms II"

    def __init__(self, player: int, name: str, parent: Region, data: LK2LocationData):
        super().__init__(player, name, data.id, parent)

        self.region = parent.name
        self.name = name
        self.data = data

lost_kingdoms_2_locations = {
    "basement chest 1": {"id": 1, "level": "Nobleman's Residence", "cardName": "Dark Raven", "isoAddress": "6D3FDB9", "missable": 0, "RAMAddress": "8025dc12", "type": "Chest", "bitOffset": 1},
    "basement chest 2": {"id": 2, "level": "Nobleman's Residence", "cardName": "Scythe Beast", "isoAddress": "6D3FE79", "missable": 0, "RAMAddress": "8025dc12", "type": "Chest", "bitOffset": 2},
    "chest near horses - Bhashea High Road": {"id": 3, "level": "Bhashea High Road", "cardName": "Porcupig", "isoAddress": "729BDF9", "missable": 0, "RAMAddress": "8025dc52", "type": "Chest", "bitOffset": 11},
    "card throw challenge": {"id": 4, "level": "Bhashea High Road", "cardName": "Elephant", "isoAddress": "72A0B9F", "missable": 1, "RAMAddress": "8025dc52", "type": "Chest", "bitOffset": 1},
    "chest near overlook - Bhashea High Road": {"id": 5, "level": "Bhashea High Road", "cardName": "Man Trap", "isoAddress": "7299BD9", "missable": 0, "RAMAddress": "8025dc52", "type": "Chest", "bitOffset": 10},
    "chest near deck point - Bhashea High Road": {"id": 6, "level": "Bhashea High Road", "cardName": "Red Lizard", "isoAddress": "729AD19", "missable": 0, "RAMAddress": "8025dc52", "type": "Chest", "bitOffset": 9},
    "jump/flight chest": {"id": 7, "level": "Bhashea High Road", "cardName": "Golden Porcupig", "isoAddress": "729C3F9", "missable": 0, "RAMAddress": "8025dc52", "type": "Chest", "bitOffset": 12},
    "red fairy across bridge": {"id": 157, "level": "Bhashea High Road", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc52", "type": "Red Fairy", "bitOffset": 8},
    "red fairy across bridge in rubble": {"id": 158, "level": "Bhashea High Road", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc52", "type": "Red Fairy", "bitOffset": 6},
    "red fairy in rubble across bridge near chaos knight": {"id": 159, "level": "Bhashea High Road", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc52", "type": "Red Fairy", "bitOffset": 7},
    "flight chest - Bhashea High Road": {"id": 8, "level": "Bhashea High Road", "cardName": "Water Moray", "isoAddress": "729B919", "missable": 0, "RAMAddress": "8025dc52", "type": "Chest", "bitOffset": 13},
    "chest outside town wall": {"id": 9, "level": "Kadishu", "cardName": "Rock Hagan", "isoAddress": "778E1D9", "missable": 0, "RAMAddress": "8025dc92", "type": "Chest", "bitOffset": 1},
    "chest up small steps": {"id": 10, "level": "Kadishu", "cardName": "Demon Hound", "isoAddress": "778DA59", "missable": 0, "RAMAddress": "8025dc92", "type": "Chest", "bitOffset": 4},
    "alleyway chest - Kadishu": {"id": 11, "level": "Kadishu", "cardName": "Dragonoid", "isoAddress": "778E119", "missable": 0, "RAMAddress": "8025dc92", "type": "Chest", "bitOffset": 5},
    "chest 4 - Kadishu": {"id": 12, "level": "Kadishu", "cardName": "Flayer Spawn", "isoAddress": "778DB19", "missable": 0, "RAMAddress": "8025dc92", "type": "Chest", "bitOffset": 3},
    "chest by dog": {"id": 13, "level": "Kadishu", "cardName": "Demon Hound", "isoAddress": "778DBD9", "missable": 0, "RAMAddress": "8025dc92", "type": "Chest", "bitOffset": 2},
    "red fairy by dog": {"id": 152, "level": "Kadishu", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc92", "type": "Red Fairy", "bitOffset": 8},
    "red fairy on bridge": {"id": 153, "level": "Kadishu", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc92", "type": "Red Fairy", "bitOffset": 10},
    "red fairy in well": {"id": 154, "level": "Kadishu", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc92", "type": "Red Fairy", "bitOffset": 6},
    "red fairy by fountain": {"id": 155, "level": "Kadishu", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc92", "type": "Red Fairy", "bitOffset": 7},
    "red fairy in alleyway": {"id": 156, "level": "Kadishu", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dc92", "type": "Red Fairy", "bitOffset": 9},
    "garbage collection 1": {"id": 14, "level": "Kadishu", "cardName": "Leprechaun", "isoAddress": "7793797", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "garbage collection 2": {"id": 15, "level": "Kadishu", "cardName": "Super Scrubber", "isoAddress": "7793A5F", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "garbage collection 3": {"id": 16, "level": "Kadishu", "cardName": "Larval Fly", "isoAddress": "77938FB", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "BC - Red Fairy near start": {"id": 240, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Red Fairy", "bitOffset": 13},
    "BC - Red Fairy central room": {"id": 242, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Red Fairy", "bitOffset": 12},
    "BC - Red Fairy rubble": {"id": 243, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Red Fairy", "bitOffset": 10},
    "BC - Red Fairy throne": {"id": 244, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Red Fairy", "bitOffset": 14},
    "BC - Red Fairy wall break rubble": {"id": 247, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Red Fairy", "bitOffset": 11},
    "BC - central room chest 1": {"id": 241, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Stones", "bitOffset": 6},
    "BC - west room chest": {"id": 246, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Stones", "bitOffset": 9},
    "BC - throne chest": {"id": 245, "level": "Bhashea Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e112", "type": "Stones", "bitOffset": 5},
    "east jump chest": {"id": 17, "level": "Bhashea Castle", "cardName": "Lamassu", "isoAddress": "C4F2A99", "missable": 0, "RAMAddress": "8025e112", "type": "Chest", "bitOffset": 2},
    "east stairway chest": {"id": 18, "level": "Bhashea Castle", "cardName": "Gorgon", "isoAddress": "C4F2D99", "missable": 0, "RAMAddress": "8025e112", "type": "Chest", "bitOffset": 7},
    "break through wall chest": {"id": 19, "level": "Bhashea Castle", "cardName": "Daidarapochi", "isoAddress": "C4F2B59", "missable": 0, "RAMAddress": "8025e112", "type": "Chest", "bitOffset": 3},
    "west room chest": {"id": 20, "level": "Bhashea Castle", "cardName": "Mole Monster", "isoAddress": "C4F2F19", "missable": 0, "RAMAddress": "8025e112", "type": "Chest", "bitOffset": 8},
    "west stairway chest": {"id": 21, "level": "Bhashea Castle", "cardName": "Death", "isoAddress": "C4F2C19", "missable": 0, "RAMAddress": "8025e112", "type": "Chest", "bitOffset": 4},
    "GD - Red Fairy 1": {"id": 248, "level": "Gromtull Desert", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "81079b44", "type": "Red Fairy", "bitOffset": 11},
    "GD - Red Fairy 2": {"id": 249, "level": "Gromtull Desert", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "81079b44", "type": "Red Fairy", "bitOffset": 12},
    "GD - Red Fairy jump": {"id": 250, "level": "Gromtull Desert", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "81079b44", "type": "Red Fairy", "bitOffset": 13},
    "GD - Red Fairy Jarvi 1": {"id": 251, "level": "Gromtull Desert", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "81079b44", "type": "Red Fairy", "bitOffset": 14},
    "GD - Red Fairy Jarvi 2": {"id": 252, "level": "Gromtull Desert", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "81079b44", "type": "Red Fairy", "bitOffset": 10},
    "chest by backpack": {"id": 22, "level": "Gromtull Desert", "cardName": "Venus Spider", "isoAddress": "C983379", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 8},
    "cave chest 1": {"id": 23, "level": "Gromtull Desert", "cardName": "Mummy", "isoAddress": "C982FB9", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 3},
    "cave chest 2": {"id": 24, "level": "Gromtull Desert", "cardName": "Pixie", "isoAddress": "C983079", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 4},
    "cave chest 3": {"id": 25, "level": "Gromtull Desert", "cardName": "Mummy", "isoAddress": "C982EF9", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 2},
    "chest by oil": {"id": 26, "level": "Gromtull Desert", "cardName": "Evil Eye", "isoAddress": "C9832B9", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 7},
    "jarvi cave chest 1": {"id": 27, "level": "Gromtull Desert", "cardName": "Running Bird", "isoAddress": "C983139", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 5},
    "jarvi cave chest 2": {"id": 28, "level": "Gromtull Desert", "cardName": "Sand Beetle", "isoAddress": "C9831F9", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 6},
    "flight chest - Gromtull Desert": {"id": 29, "level": "Gromtull Desert", "cardName": "Bum Hagan", "isoAddress": "C983439", "missable": 0, "RAMAddress": "81079b44", "type": "Chest", "bitOffset": 9},
    "Red Fairy at start": {"id": 160, "level": "Kendarie Fortress", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dcd2", "type": "Red Fairy", "bitOffset": 11},
    "Red Fairy fly across": {"id": 161, "level": "Kendarie Fortress", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dcd2", "type": "Red Fairy", "bitOffset": 10},
    "Red Fairy past blue gate": {"id": 162, "level": "Kendarie Fortress", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dcd2", "type": "Red Fairy", "bitOffset": 8},
    "Red Fairy near Mechapult": {"id": 163, "level": "Kendarie Fortress", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dcd2", "type": "Red Fairy", "bitOffset": 9},
    "chest 1 - Kendarie Fortress": {"id": 30, "level": "Kendarie Fortress", "cardName": "Mandragora", "isoAddress": "7C12519", "missable": 0, "RAMAddress": "8025dcd2", "type": "Chest", "bitOffset": 2},
    "chest 2 - Kendarie Fortress": {"id": 31, "level": "Kendarie Fortress", "cardName": "Aggressor GL2", "isoAddress": "7C154B9", "missable": 0, "RAMAddress": "8025dcd2", "type": "Chest", "bitOffset": 4},
    "chest behind green door": {"id": 32, "level": "Kendarie Fortress", "cardName": "Death", "isoAddress": "7C153F9", "missable": 0, "RAMAddress": "8025dcd2", "type": "Chest", "bitOffset": 3},
    "chest 4 - Kendarie Fortress": {"id": 33, "level": "Kendarie Fortress", "cardName": "Venom Lizard", "isoAddress": "7C156F9", "missable": 0, "RAMAddress": "8025dcd2", "type": "Chest", "bitOffset": 6},
    "chest 5 - Kendarie Fortress": {"id": 34, "level": "Kendarie Fortress", "cardName": "MechaPult", "isoAddress": "7C15579", "missable": 0, "RAMAddress": "8025dcd2", "type": "Chest", "bitOffset": 5},
    "flight chest - Kendarie Fortress": {"id": 35, "level": "Kendarie Fortress", "cardName": "UberBomberBot", "isoAddress": "7C14979", "missable": 0, "RAMAddress": "8025dcd2", "type": "Chest", "bitOffset": 7},
    "Red Fairy near start": {"id": 164, "level": "Runestone Caverns - Upper Chambers", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd12", "type": "Red Fairy", "bitOffset": 13},
    "Red Fairy near sluice gate": {"id": 165, "level": "Runestone Caverns - Upper Chambers", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd12", "type": "Red Fairy", "bitOffset": 9},
    "Red Fairy near dragon": {"id": 166, "level": "Runestone Caverns - Upper Chambers", "cardName": "","isoAddress": "", "missable": 0, "RAMAddress": "8025dd12", "type": "Red Fairy", "bitOffset": 10},
    "Red Fairy near golem": {"id": 167, "level": "Runestone Caverns - Upper Chambers", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd12", "type": "Red Fairy", "bitOffset": 11},
    "Red Fairy near Sol": {"id": 168, "level": "Runestone Caverns - Upper Chambers", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd12", "type": "Red Fairy", "bitOffset": 12},
    "chest 1 - Runestone Caverns - Upper Chambers": {"id": 36, "level": "Runestone Caverns - Upper Chambers", "cardName": "Dark Raven", "isoAddress": "8025dd12", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": 14},
    "chest 2 - Runestone Caverns - Upper Chambers": {"id": 37, "level": "Runestone Caverns - Upper Chambers", "cardName": "Land Shark", "isoAddress": "8025dd12", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": 6},
    "talk to Sol": {"id": 38, "level": "Runestone Caverns - Upper Chambers", "cardName": "Stone Golem", "isoAddress": "7FC9CD7", "missable": 1, "RAMAddress": "8025dd12", "type": "Chest", "bitOffset": 1},
    "lower chest 1": {"id": 39, "level": "Runestone Caverns - Upper Chambers", "cardName": "Blood Bush", "isoAddress": "7FC8639", "missable": 0, "RAMAddress": "8025dd12", "type": "Chest", "bitOffset": 8},
    "lower chest 2": {"id": 40, "level": "Runestone Caverns - Upper Chambers", "cardName": "Undine", "isoAddress": "7FC83F9", "missable": 0, "RAMAddress": "8025dd12", "type": "Chest", "bitOffset": 4},
    "chest behind ice 1": {"id": 41, "level": "Runestone Caverns - Upper Chambers", "cardName": "Gorgon", "isoAddress": "7FC86F9", "missable": 0, "RAMAddress": "8025dd12", "type": "Chest", "bitOffset": 7},
    "chest behind ice 2": {"id": 42, "level": "Runestone Caverns - Upper Chambers", "cardName": "Land Shark", "isoAddress": "7FC84B9", "missable": 0, "RAMAddress": "8025dd12", "type": "Chest", "bitOffset": 5},
    "dragon chest 1": {"id": 43, "level": "Runestone Caverns - Upper Chambers", "cardName": "Baba Yaga", "isoAddress": "7FC8339", "missable": 0, "RAMAddress": "8025dd12", "type": "Chest", "bitOffset": 2},
    "dragon chest 2": {"id": 44, "level": "Runestone Caverns - Upper Chambers", "cardName": "Witchlette", "isoAddress": "7FC8279", "missable": 0, "RAMAddress": "8025dd12", "type": "Chest", "bitOffset": 3},
    "RC-LC Red Fairy near start": {"id": 169, "level": "Runestone Caverns - Lower Chambers", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 9},
    "Red Fairy low water": {"id": 170, "level": "Runestone Caverns - Lower Chambers", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 12},
    "Red Fairy on stairs": {"id": 171, "level": "Runestone Caverns - Lower Chambers", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 10},
    "chest 1 - Runestone Caverns - Lower Chambers": {"id": 45, "level": "Runestone Caverns - Lower Chambers", "cardName": "Flayer Spawn", "isoAddress": "843A839", "missable": 0, "RAMAddress": "8025dd52", "type": "Chest", "bitOffset": 2},
    "chest 2 - Runestone Caverns - Lower Chambers": {"id": 46, "level": "Runestone Caverns - Lower Chambers", "cardName": "Basilisk", "isoAddress": "843B079", "missable": 0, "RAMAddress": "8025dd52", "type": "Chest", "bitOffset": 8},
    "low water chest": {"id": 47, "level": "Runestone Caverns - Lower Chambers", "cardName": "Maelstrom", "isoAddress": "843A9B9", "missable": 0, "RAMAddress": "8025dd52", "type": "Chest", "bitOffset": 4},
    "high water chest 1": {"id": 48, "level": "Runestone Caverns - Lower Chambers", "cardName": "Yowie", "isoAddress": "843A8F9", "missable": 0, "RAMAddress": "8025dd52", "type": "Chest", "bitOffset": 3},
    "high water chest flight": {"id": 49, "level": "Runestone Caverns - Lower Chambers", "cardName": "Maelstrom", "isoAddress": "843AB39", "missable": 0, "RAMAddress": "8025dd52", "type": "Chest", "bitOffset": 5},
    "chest 6": {"id": 50, "level": "Runestone Caverns - Lower Chambers", "cardName": "Flayer Spawn", "isoAddress": "843ABF9", "missable": 0, "RAMAddress": "8025dd52", "type": "Chest", "bitOffset": 7},
    "chest 7": {"id": 51, "level": "Runestone Caverns - Lower Chambers", "cardName": "Flayer Spawn", "isoAddress": "843ACB9", "missable": 0, "RAMAddress": "8025dd52", "type": "Chest", "bitOffset": 6},
    "RF Red Fairy at start": {"id": 172, "level": "Ruldo Forest", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 9},
    "RF Red Fairy at start 2": {"id": 173, "level": "Ruldo Forest", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 13},
    "RF Red Fairy in tree": {"id": 174, "level": "Ruldo Forest", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 12},
    "RF Red Fairy near machine": {"id": 175, "level": "Ruldo Forest", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 10},
    "RF Red past Cockatrice": {"id": 176, "level": "Ruldo Forest", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 11},
    "chest 1 - Ruldo Forest": {"id": 52, "level": "Ruldo Forest", "cardName": "Mandragora", "isoAddress": "885D979", "missable": 0, "RAMAddress": "8025dd92", "type": "Chest", "bitOffset": 2},
    "chest 2 - Ruldo Forest": {"id": 177, "level": "Ruldo Forest", "cardName": "", "isoAddress": "885D979", "missable": 0, "RAMAddress": "8025dd92", "type": "Stones", "bitOffset": 3},
    "chest 3 - Ruldo Forest": {"id": 53, "level": "Ruldo Forest", "cardName": "Dryad", "isoAddress": "885DD39", "missable": 0, "RAMAddress": "8025dd92", "type": "Chest", "bitOffset": 4},
    "jump chest - Ruldo Forest": {"id": 54, "level": "Ruldo Forest", "cardName": "Elf", "isoAddress": "885DDF9", "missable": 0, "RAMAddress": "8025dd92", "type": "Chest", "bitOffset": 5},
    "flight/jump chest - Ruldo Forest": {"id": 55, "level": "Ruldo Forest", "cardName": "Night Mare", "isoAddress": "885DEB9", "missable": 0, "RAMAddress": "8025dd92", "type": "Chest", "bitOffset": 6},
    "cockatrice chest 1": {"id": 56, "level": "Ruldo Forest", "cardName": "Demon Hound", "isoAddress": "885E039", "missable": 0, "RAMAddress": "8025dd92", "type": "Chest", "bitOffset": 8},
    "cockatrice chest 2": {"id": 57, "level": "Ruldo Forest", "cardName": "Raflesia", "isoAddress": "885DF79", "missable": 0, "RAMAddress": "8025dd92", "type": "Chest", "bitOffset": 7},
    "defeat Lich": {"id": 58, "level": "Sacred Battle Arena 1", "cardName": "Lich", "isoAddress": "CDB809B", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Nueh": {"id": 59, "level": "Sacred Battle Arena 1", "cardName": "Nueh", "isoAddress": "CDB78E3", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Gemini": {"id": 60, "level": "Sacred Battle Arena 1", "cardName": "Gemini", "isoAddress": "CDB7CBF", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Kraken": {"id": 61, "level": "Sacred Battle Arena 1", "cardName": "Kraken", "isoAddress": "CDB8477", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Rabandos": {"id": 62, "level": "Sacred Battle Arena 2", "cardName": "Rabandos", "isoAddress": "D293F83", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Helena": {"id": 63, "level": "Sacred Battle Arena 2", "cardName": "Ice Skeleton", "isoAddress": "D2943DF", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Astrobot": {"id": 64, "level": "Sacred Battle Arena 2", "cardName": "AstroBot", "isoAddress": "D29375B", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Leod": {"id": 65, "level": "Sacred Battle Arena 2", "cardName": "Sacred Umpire", "isoAddress": "D293B6F", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Thalnos": {"id": 66, "level": "Sacred Battle Arena 2", "cardName": "Sekmet", "isoAddress": "D2947FF", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "defeat Katia": {"id": 67, "level": "Sacred Battle Arena 2", "cardName": "Doppelganger", "isoAddress": "D294C3F", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "FB - Red Fairy near start": {"id": 178, "level": "Fossil Boneyard", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 12},
    "FB - Red Fairy near jump pad": {"id": 179, "level": "Fossil Boneyard", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 13},
    "FB - Red Fairy jumping": {"id": 179, "level": "Fossil Boneyard", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dd52", "type": "Red Fairy", "bitOffset": 14},
    "chest 1 - Fossil Boneyard": {"id": 68, "level": "Fossil Boneyard", "cardName": "Hell Hound", "isoAddress": "B45E8C9", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 2},
    "chest behind cultist": {"id": 69, "level": "Fossil Boneyard", "cardName": "Gnome", "isoAddress": "B45E939", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 9},
    "chest 3 - Fossil Boneyard": {"id": 70, "level": "Fossil Boneyard", "cardName": "Hell Hound", "isoAddress": "B45E9F9", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 4},
    "chest 4 - Fossil Boneyard": {"id": 71, "level": "Fossil Boneyard", "cardName": "Hell Hound", "isoAddress": "B45E7B9", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 7},
    "chest 5 - Fossil Boneyard": {"id": 72, "level": "Fossil Boneyard", "cardName": "Caterpoker", "isoAddress": "B45EAB9", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 5},
    "chest 6 - Fossil Boneyard": {"id": 180, "level": "Fossil Boneyard", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025e012", "type": "Stones", "bitOffset": 6},
    "chest 7 - Fossil Boneyard": {"id": 73, "level": "Fossil Boneyard", "cardName": "Dark Raven", "isoAddress": "B45EC39", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 8},
    "flight chest 1": {"id": 74, "level": "Fossil Boneyard", "cardName": "Catoblepas", "isoAddress": "B45ECF9", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 10},
    "flight chest 2 - Fossil Boneyard": {"id": 75, "level": "Fossil Boneyard", "cardName": "Amber Dragon", "isoAddress": "B45EDB9", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 11},
    "zombie dragon chest": {"id": 76, "level": "Fossil Boneyard", "cardName": "Zombie Dragon", "isoAddress": "B45CB99", "missable": 0, "RAMAddress": "8025e012", "type": "Chest", "bitOffset": 3},
    "Sarvan - Red Fairy near start": {"id": 181, "level": "Sarvan", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025ddd2", "type": "Red Fairy", "bitOffset": 11},
    "Sarvan - Red Fairy under bridge": {"id": 183, "level": "Sarvan", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025ddd2", "type": "Red Fairy", "bitOffset": 13},
    "Sarvan - Red Fairy magic circle": {"id": 184, "level": "Sarvan", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025ddd2", "type": "Red Fairy", "bitOffset": 12},
    "jump chest - Sarvan": {"id": 77, "level": "Sarvan", "cardName": "Marid", "isoAddress": "8CCC9D9", "missable": 0, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 4},
    "chest 1 - Sarvan": {"id": 78, "level": "Sarvan", "cardName": "Decoy Pillar", "isoAddress": "8CCCAF9", "missable": 0, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 5},
    "chest 2 - Sarvan": {"id": 79, "level": "Sarvan", "cardName": "Jade Giant", "isoAddress": "8CCCBB9", "missable": 0, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 6},
    "chest 3 - Sarvan": {"id": 182, "level": "Sarvan", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025ddd2", "type": "Stones", "bitOffset": 7},
    "caged chest": {"id": 80, "level": "Sarvan", "cardName": "Lucky Lion", "isoAddress": "8CCC859", "missable": 1, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 2},
    "chest 4 - Sarvan": {"id": 81, "level": "Sarvan", "cardName": "Mandragora", "isoAddress": "8CCCDF9", "missable": 0, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 9},
    "chest 5 - Sarvan": {"id": 82, "level": "Sarvan", "cardName": "Gold Butterfly", "isoAddress": "8CCCD39", "missable": 0, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 8},
    "caged chest 2": {"id": 83, "level": "Sarvan", "cardName": "Hobgoblin", "isoAddress": "8CCC919", "missable": 1, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 3},
    "puzzle chest": {"id": 84, "level": "Sarvan", "cardName": "Devata", "isoAddress": "8CCE0B9", "missable": 0, "RAMAddress": "8025ddd2", "type": "Chest", "bitOffset": 10},
    "HT - Red Fairy near start": {"id": 185, "level": "Holzogh Town", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025ddd2", "type": "Red Fairy", "bitOffset": 12},
    "HT - Red Fairy stairs": {"id": 186, "level": "Holzogh Town", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025ddd2", "type": "Red Fairy", "bitOffset": 14},
    "HT - Red Fairy rubble": {"id": 187, "level": "Holzogh Town", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025ddd2", "type": "Red Fairy", "bitOffset": 11},
    "HT - Red Fairy rubble 2": {"id": 189, "level": "Holzogh Town", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025ddd2", "type": "Red Fairy", "bitOffset": 15},
    "chest 1 - Holzogh Town": {"id": 85, "level": "Holzogh Town", "cardName": "Red Lizard", "isoAddress": "920A899", "missable": 0, "RAMAddress": "8025de12", "type": "Chest", "bitOffset": 4},
    "chest 2 - Holzogh Town": {"id": 86, "level": "Holzogh Town", "cardName": "Efreet", "isoAddress": "920AA19", "missable": 0, "RAMAddress": "8025de12", "type": "Chest", "bitOffset": 8},
    "chest 3 - Holzogh Town": {"id": 186, "level": "Holzogh Town", "cardName": "", "isoAddress": "","missable": 0, "RAMAddress": "8025de12", "type": "Stones", "bitOffset": 5},
    "chest 4 - Holzogh Town": {"id": 87, "level": "Holzogh Town", "cardName": "Coal Treant", "isoAddress": "920A7D9", "missable": 0, "RAMAddress": "8025de12", "type": "Chest", "bitOffset": 2},
    "chest 5 - Holzogh Town": {"id": 88, "level": "Holzogh Town", "cardName": "Salamander", "isoAddress": "920AB99", "missable": 0, "RAMAddress": "8025de12", "type": "Chest", "bitOffset": 7},
    "chest 6 - Holzogh Town": {"id": 89, "level": "Holzogh Town", "cardName": "Popgun Charlie", "isoAddress": "920AAD9", "missable": 0, "RAMAddress": "8025de12", "type": "Chest", "bitOffset": 6},
    "chest 7 - Holzogh Town": {"id": 188, "level": "Holzogh Town", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025de12", "type": "Stones", "bitOffset": 10},
    "fountain card": {"id": 90, "level": "Holzogh Town", "cardName": "Mind Flayer", "isoAddress": "9209AB9", "missable": 1, "RAMAddress": "8025de12", "type": "Chest", "bitOffset": 3},
    "PoR Red Fairy near start": {"id": 190, "level": "Plains of Rowahl", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025de52", "type": "Red Fairy", "bitOffset": 12},
    "PoR Red Fairy in golem": {"id": 191, "level": "Plains of Rowahl", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025de52", "type": "Red Fairy", "bitOffset": 14},
    "PoR Red Fairy past gate": {"id": 193, "level": "Plains of Rowahl", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025de52", "type": "Red Fairy", "bitOffset": 15},
    "chest 1 - Plains of Rowahl": {"id": 91, "level": "Plains of Rowahl", "cardName": "Devil Plant", "isoAddress": "96780F9", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 5},
    "chest 2 - Plains of Rowahl": {"id": 92, "level": "Plains of Rowahl", "cardName": "Sand Golem", "isoAddress": "9678219", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 6},
    "flight chest - Plains of Rowahl": {"id": 192, "level": "Plains of Rowahl", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025de52", "type": "Stones", "bitOffset": 8},
    "chest under scrap": {"id": 93, "level": "Plains of Rowahl", "cardName": "Dao", "isoAddress": "9678CF9", "missable": 1, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 9},
    "chest 4 - Plains of Rowahl": {"id": 94, "level": "Plains of Rowahl", "cardName": "Man Trap", "isoAddress": "9678519", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 11},
    "chest 5 - Plains of Rowahl": {"id": 95, "level": "Plains of Rowahl", "cardName": "Night Mare", "isoAddress": "9678459", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 10},
    "chest 6 - Plains of Rowahl": {"id": 227, "level": "Plains of Rowahl", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 3},
    "chest 7 - Plains of Rowahl": {"id": 228, "level": "Plains of Rowahl", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 4},
    "flight chest 2 - Plains of Rowahl": {"id": 96, "level": "Plains of Rowahl", "cardName": "King Mandragora", "isoAddress": "96782D9", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": 7},
    "GoD card": {"id": 97, "level": "Plains of Rowahl", "cardName": "God of Destruction", "isoAddress": "967A757", "missable": 0, "RAMAddress": "8025de52", "type": "Chest", "bitOffset": -1},
    "AC Red Fairy near start": {"id": 194, "level": "Alanjeh Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025de92", "type": "Red Fairy", "bitOffset": 10},
    "AC Red Fairy jump": {"id": 195, "level": "Alanjeh Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025de92", "type": "Red Fairy", "bitOffset": 9},
    "AC Red Fairy end": {"id": 196, "level": "Alanjeh Castle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025de92", "type": "Red Fairy", "bitOffset": 10},
    "chest 2 - Alanjeh Castle": {"id": 98, "level": "Alanjeh Castle", "cardName": "AcidBot", "isoAddress": "9A83399", "missable": 0, "RAMAddress": "8025de92", "type": "Chest", "bitOffset": 4},
    "chest 3 - Alanjeh Castle": {"id": 99, "level": "Alanjeh Castle", "cardName": "Dark Treant", "isoAddress": "9A832D9", "missable": 0, "RAMAddress": "8025de92", "type": "Chest", "bitOffset": 3},
    "chest 4 - Alanjeh Castle": {"id": 100, "level": "Alanjeh Castle", "cardName": "Gizmolizer", "isoAddress": "9A83699", "missable": 0, "RAMAddress": "8025de92", "type": "Chest", "bitOffset": 8},
    "chest 5 - Alanjeh Castle": {"id": 101, "level": "Alanjeh Castle", "cardName": "Fairy", "isoAddress": "9A83459", "missable": 0, "RAMAddress": "8025de92", "type": "Chest", "bitOffset": 5},
    "chest 6 - Alanjeh Castle": {"id": 197, "level": "Alanjeh Castle", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025de92", "type": "Stones", "bitOffset": 6},
    "flight chest - Alanjeh Castle": {"id": 102, "level": "Alanjeh Castle", "cardName": "Boom Monkey", "isoAddress": "9A835D9", "missable": 0, "RAMAddress": "8025de92", "type": "Chest", "bitOffset": 7},
    "RTL Red Fairy start": {"id": 198, "level": "Royal Tower, Lower", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025ded2", "type": "Red Fairy", "bitOffset": 4},
    "RTL Red Fairy up elevator": {"id": 199, "level": "Royal Tower, Lower", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025ded2", "type": "Red Fairy", "bitOffset": 5},
    "RTL Red Fairy over pillar": {"id": 200, "level": "Royal Tower, Lower", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e052", "type": "Red Fairy", "bitOffset": 8},
    "RTL Red Fairy chandelier": {"id": 201, "level": "Royal Tower, Lower", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e052", "type": "Red Fairy", "bitOffset": 9},
    "RTL Red Fairy outside": {"id": 202, "level": "Royal Tower, Lower", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e052", "type": "Red Fairy", "bitOffset": 11},
    "RTL Red Fairy flight": {"id": 229, "level": "Royal Tower, Lower", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e052", "type": "Red Fairy", "bitOffset": 10},
    "chest 1 - Royal Tower, Lower": {"id": 103, "level": "Royal Tower, Lower", "cardName": "Carbuncle", "isoAddress": "9F0DE19", "missable": 1, "RAMAddress": "8025ded2", "type": "Chest", "bitOffset": 2},
    "chest 2 - Royal Tower, Lower": {"id": 104, "level": "Royal Tower, Lower", "cardName": "Sprite", "isoAddress": "9F0DED9", "missable": 1, "RAMAddress": "8025ded2", "type": "Chest", "bitOffset": 3},
    "chest 3 - Royal Tower, Lower": {"id": 105, "level": "Royal Tower, Lower", "cardName": "Tiger Mage", "isoAddress": "B949EB9", "missable": 1, "RAMAddress": "8025e052", "type": "Chest", "bitOffset": 2},
    "flight chest 1 - Royal Tower, Lower": {"id": 230, "level": "Royal Tower, Lower", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025e052", "type": "Stones", "bitOffset": 4},
    "flight chest 2 - Royal Tower, Lower": {"id": 106, "level": "Royal Tower, Lower", "cardName": "Puppet Master", "isoAddress": "B949F79", "missable": 0, "RAMAddress": "8025e052", "type": "Chest", "bitOffset": 3},
    "jump chest 1": {"id": 107, "level": "Royal Tower, Lower", "cardName": "Decoy Pillar", "isoAddress": "B94A0F9", "missable": 0, "RAMAddress": "8025e052", "type": "Chest", "bitOffset": 5},
    "jump chest 2": {"id": 108, "level": "Royal Tower, Lower", "cardName": "Fire Gargoyle", "isoAddress": "B94A1B9", "missable": 0, "RAMAddress": "8025e052", "type": "Chest", "bitOffset": 6},
    "RTM Red Fairy near start": {"id": 231, "level": "Royal Tower, Middle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df92", "type": "Red Fairy", "bitOffset": 8},
    "RTM Red Fairy hallway": {"id": 233, "level": "Royal Tower, Middle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df92", "type": "Red Fairy", "bitOffset": 10},
    "RTM Red Fairy breakable wall 1": {"id": 234, "level": "Royal Tower, Middle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df92", "type": "Red Fairy", "bitOffset": 9},
    "RTM Red Fairy breakable wall 2": {"id": 235, "level": "Royal Tower, Middle", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df92", "type": "Red Fairy", "bitOffset": 11},
    "chest 1 - Royal Tower, Middle": {"id": 109, "level": "Royal Tower, Middle", "cardName": "Rheebus", "isoAddress": "ABD9259", "missable": 0, "RAMAddress": "8025df92", "type": "Chest", "bitOffset": 4},
    "chest 2 - Royal Tower, Middle": {"id": 232, "level": "Royal Tower, Middle", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025df92", "type": "Stones", "bitOffset": 5},
    "breakable wall chest 1": {"id": 110, "level": "Royal Tower, Middle", "cardName": "Sphinx", "isoAddress": "ABD9139", "missable": 0, "RAMAddress": "8025df92", "type": "Chest", "bitOffset": 3},
    "breakable wall chest 2": {"id": 111, "level": "Royal Tower, Middle", "cardName": "Hydra", "isoAddress": "ABD9079", "missable": 0, "RAMAddress": "8025df92", "type": "Chest", "bitOffset": 2},
    "forcefield chest 1": {"id": 112, "level": "Royal Tower, Middle", "cardName": "Unicorn", "isoAddress": "ABD93D9", "missable": 1, "RAMAddress": "8025df92", "type": "Chest", "bitOffset": 6},
    "forcefield chest 2": {"id": 113, "level": "Royal Tower, Middle", "cardName": "Red Dragon", "isoAddress": "ABD9499", "missable": 1, "RAMAddress": "8025df92", "type": "Chest", "bitOffset": 7},
    "RTU Red Fairy rubble": {"id": 236, "level": "Royal Tower, Upper", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dfd2", "type": "Red Fairy", "bitOffset": 5},
    "RTU Red Fairy sphinx": {"id": 237, "level": "Royal Tower, Upper", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dfd2", "type": "Red Fairy", "bitOffset": 7},
    "RTU Red Fairy stairs 1": {"id": 238, "level": "Royal Tower, Upper", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dfd2", "type": "Red Fairy", "bitOffset": 8},
    "RTU Red Fairy stairs 2": {"id": 239, "level": "Royal Tower, Upper", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025dfd2", "type": "Red Fairy", "bitOffset": 6},
    "chest 1 - Royal Tower, Upper": {"id": 114, "level": "Royal Tower, Upper", "cardName": "Wyvern", "isoAddress": "B02D5B9", "missable": 0, "RAMAddress": "8025dfd2", "type": "Chest", "bitOffset": 2},
    "chest 2 - Royal Tower, Upper": {"id": 115, "level": "Royal Tower, Upper", "cardName": "Unicorn", "isoAddress": "B02D679", "missable": 0, "RAMAddress": "8025dfd2", "type": "Chest", "bitOffset": 4},
    "chest 3 - Royal Tower, Upper": {"id": 116, "level": "Royal Tower, Upper", "cardName": "Spartoi", "isoAddress": "B02D739", "missable": 0, "RAMAddress": "8025dfd2", "type": "Chest", "bitOffset": 3},
    "black dragon's card": {"id": 117, "level": "Krasheen Mountains", "cardName": "Birdman", "isoAddress": "A25D29F", "missable": 1, "RAMAddress": "8025df12", "type": "Chest", "bitOffset": -1},
    "KM Red Fairy cave 1": {"id": 203, "level": "Krasheen Mountains", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df12", "type": "Red Fairy", "bitOffset": 10},
    "KM Red Fairy bridge": {"id": 204, "level": "Krasheen Mountains", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df12", "type": "Red Fairy", "bitOffset": 9},
    "KM Red Fairy broken bridge": {"id": 206, "level": "Krasheen Mountains", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df12", "type": "Red Fairy", "bitOffset": 11},
    "KM Red Fairy broken bridge 2": {"id": 208, "level": "Krasheen Mountains", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df12", "type": "Red Fairy", "bitOffset": 12},
    "chest 1 - Krasheen Mountains": {"id": 118, "level": "Krasheen Mountains", "cardName": "Birdman", "isoAddress": "A25AED9", "missable": 0, "RAMAddress": "8025df12", "type": "Chest", "bitOffset": 2},
    "chest 2 - Krasheen Mountains": {"id": 119, "level": "Krasheen Mountains", "cardName": "Charadrius", "isoAddress": "A25B059", "missable": 0, "RAMAddress": "8025df12", "type": "Chest", "bitOffset": 5},
    "chest 3 - Krasheen Mountains": {"id": 120, "level": "Krasheen Mountains", "cardName": "Birdman", "isoAddress": "A25AE19", "missable": 0, "RAMAddress": "8025df12", "type": "Chest", "bitOffset": 3},
    "chest 4 - Krasheen Mountains": {"id": 205, "level": "Krasheen Mountains", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025df12", "type": "Stones", "bitOffset": 4},
    "chest 7 - Krasheen Mountains": {"id": 206, "level": "Krasheen Mountains", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025df12", "type": "Stones", "bitOffset": 8},
    "chest 5 - Krasheen Mountains": {"id": 121, "level": "Krasheen Mountains", "cardName": "Acid Dragon", "isoAddress": "A25B1D9", "missable": 0, "RAMAddress": "8025df12", "type": "Chest", "bitOffset": 6},
    "chest 6 - Krasheen Mountains": {"id": 122, "level": "Krasheen Mountains", "cardName": "Earth Moray", "isoAddress": "A25B119", "missable": 0, "RAMAddress": "8025df12", "type": "Chest", "bitOffset": 7},
    "GC - Red Fairy near organ": {"id": 214, "level": "Grenfoel Church", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df52", "type": "Red Fairy", "bitOffset": 7},
    "GC - Red Fairy right side": {"id": 215, "level": "Grenfoel Church", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df52", "type": "Red Fairy", "bitOffset": 10},
    "GC - Red Fairy hidden 1": {"id": 216, "level": "Grenfoel Church", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df52", "type": "Red Fairy", "bitOffset": 9},
    "GC - Red Fairy hidden 2": {"id": 217, "level": "Grenfoel Church", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df52", "type": "Red Fairy", "bitOffset": 11},
    "GC - Red Fairy library": {"id": 218, "level": "Grenfoel Church", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025df52", "type": "Red Fairy", "bitOffset": 8},
    "hidden chest 1": {"id": 218, "level": "Grenfoel Church", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025df52", "type": "Stones", "bitOffset": 4},
    "hidden chest 2": {"id": 123, "level": "Grenfoel Church", "cardName": "Vampire", "isoAddress": "A72FD39", "missable": 0, "RAMAddress": "8025df52", "type": "Chest", "bitOffset": 2},
    "hidden chest 3": {"id": 124, "level": "Grenfoel Church", "cardName": "Plague Rat", "isoAddress": "A72FDF9", "missable": 0, "RAMAddress": "8025df52", "type": "Chest", "bitOffset": 3},
    "organ chest 1": {"id": 219, "level": "Grenfoel Church", "cardName": "", "isoAddress": "","missable": 0, "RAMAddress": "8025df52", "type": "Stones", "bitOffset": 6},
    "organ chest 2": {"id": 125, "level": "Grenfoel Church", "cardName": "Gravity Pillar", "isoAddress": "A72FF79", "missable": 0, "RAMAddress": "8025df52", "type": "Chest", "bitOffset": 5},
    "ToS - Red Fairy near start": {"id": 220, "level": "Temple of Sharacia", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e292", "type": "Red Fairy", "bitOffset": 9},
    "ToS - Red Fairy near start 2": {"id": 221, "level": "Temple of Sharacia", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e292", "type": "Red Fairy", "bitOffset": 10},
    "ToS - Red Fairy up left stairs": {"id": 222, "level": "Temple of Sharacia", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e292", "type": "Red Fairy", "bitOffset": 14},
    "ToS - Red Fairy up right side": {"id": 224, "level": "Temple of Sharacia", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e292", "type": "Red Fairy", "bitOffset": 11},
    "ToS - Red Fairy up left side": {"id": 225, "level": "Temple of Sharacia", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e292", "type": "Red Fairy", "bitOffset": 11},
    "flight chest - Temple of Sharacia": {"id": 126, "level": "Temple of Sharacia", "cardName": "Cerberus", "isoAddress": "DBBBBD9", "missable": 0, "RAMAddress": "8025e292", "type": "Chest", "bitOffset": 2},
    "chest 1 - Temple of Sharacia": {"id": 127, "level": "Temple of Sharacia", "cardName": "Salamander", "isoAddress": "DBBBD59", "missable": 0, "RAMAddress": "8025e292", "type": "Chest", "bitOffset": 4},
    "chest 2 - Temple of Sharacia": {"id": 128, "level": "Temple of Sharacia", "cardName": "Hell Hound", "isoAddress": "DBBBC99", "missable": 0, "RAMAddress": "8025e292", "type": "Chest", "bitOffset": 3},
    "chest 3 - Temple of Sharacia": {"id": 223, "level": "Temple of Sharacia", "cardName": "","isoAddress": "", "missable": 0, "RAMAddress": "8025e292", "type": "Stones","bitOffset": 5},
    "chest 4 - Temple of Sharacia": {"id": 226, "level": "Temple of Sharacia", "cardName": "","isoAddress": "", "missable": 0, "RAMAddress": "8025e292", "type": "Stones","bitOffset": 7},
    "chest 5 - Temple of Sharacia": {"id": 129, "level": "Temple of Sharacia", "cardName": "Fire Elemental", "isoAddress": "DBBC059", "missable": 0, "RAMAddress": "8025e292", "type": "Chest", "bitOffset": 8},
    "chest 6 - Temple of Sharacia": {"id": 130, "level": "Temple of Sharacia", "cardName": "Fire Gargoyle", "isoAddress": "DBBBE19", "missable": 0, "RAMAddress": "8025e292", "type": "Chest", "bitOffset": 6},
    "help valkyrie": {"id": 131, "level": "Temple of Sharacia", "cardName": "Valkyrie", "isoAddress": "DBBE7FD", "missable": 1, "RAMAddress": "8025e292", "type": "Chest", "bitOffset": -1},
    "help ashura": {"id": 132, "level": "Temple of Sharacia", "cardName": "Ashura", "isoAddress": "DBBE4A7", "missable": 1, "RAMAddress": "8025e292", "type": "Chest", "bitOffset": -1},
    "chest 1 - Isamat Urbur": {"id": 133, "level": "Isamat Urbur", "cardName": "Green Dragon", "isoAddress": "BFF2A19", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "chest 3 - Isamat Urbur": {"id": 134, "level": "Isamat Urbur", "cardName": "Succubus", "isoAddress": "BFF2B99", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "chest 5 - Isamat Urbur": {"id": 135, "level": "Isamat Urbur", "cardName": "Incubus", "isoAddress": "BFF2AD9", "missable": 0, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "OG - Red Fairy near start": {"id": 209, "level": "Obenoix Gorge", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e212", "type": "Red Fairy", "bitOffset": 9},
    "OG - Red Fairy in tree": {"id": 210, "level": "Obenoix Gorge", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e212", "type": "Red Fairy", "bitOffset": 11},
    "OG - Red Fairy near flight": {"id": 211, "level": "Obenoix Gorge", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e212", "type": "Red Fairy", "bitOffset": 10},
    "OG - Red Fairy in tree 2": {"id": 213, "level": "Obenoix Gorge", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e212", "type": "Red Fairy", "bitOffset": 12},
    "OG - Red Fairy near ship": {"id": 2143, "level": "Obenoix Gorge", "cardName": "", "isoAddress": "", "missable": 0,"RAMAddress": "8025e212", "type": "Red Fairy", "bitOffset": 13},
    "chest 1 - Obenoix Gorge": {"id": 136, "level": "Obenoix Gorge", "cardName": "Water Elemental", "isoAddress": "D7106D9", "missable": 0, "RAMAddress": "8025e212", "type": "Chest", "bitOffset": 2},
    "chest 2 - Obenoix Gorge": {"id": 137, "level": "Obenoix Gorge", "cardName": "Sasquatch", "isoAddress": "D710799", "missable": 0, "RAMAddress": "8025e212", "type": "Chest", "bitOffset": 3},
    "flight chest 1 - Obenoix Gorge": {"id": 212, "level": "Obenoix Gorge", "cardName": "", "isoAddress": "", "missable": 0, "RAMAddress": "8025e212", "type": "Stones", "bitOffset": 5},
    "flight chest 2 - Obenoix Gorge": {"id": 138, "level": "Obenoix Gorge", "cardName": "Crystal Rose", "isoAddress": "D710859", "missable": 0, "RAMAddress": "8025e212", "type": "Chest", "bitOffset": 4},
    "chest 3 - Obenoix Gorge": {"id": 139, "level": "Obenoix Gorge", "cardName": "Siren", "isoAddress": "D710A99", "missable": 0, "RAMAddress": "8025e212", "type": "Chest", "bitOffset": 7},
    "chest 4 - Obenoix Gorge": {"id": 140, "level": "Obenoix Gorge", "cardName": "Chameleus", "isoAddress": "D7109D9", "missable": 0, "RAMAddress": "8025e212", "type": "Chest", "bitOffset": 6},
    "chest behind ice": {"id": 141, "level": "Obenoix Gorge", "cardName": "Thanatos", "isoAddress": "D710D99", "missable": 0, "RAMAddress": "8025e212", "type": "Chest", "bitOffset": 14},
    "flight chest 3": {"id": 142, "level": "Obenoix Gorge", "cardName": "Hydra", "isoAddress": "D710B59", "missable": 0, "RAMAddress": "8025e212", "type": "Chest", "bitOffset": 8},
    "collect 1 fairy": {"id": 143, "level": "Fairy House", "cardName": "Tumble Chick", "isoAddress": "183A31", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 10 fairies": {"id": 144, "level": "Fairy House", "cardName": "Carbuncle", "isoAddress": "183A33", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 20 fairies": {"id": 145, "level": "Fairy House", "cardName": "Berserker", "isoAddress": "183A35", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 30 fairies": {"id": 146, "level": "Fairy House", "cardName": "Fire Moray", "isoAddress": "183A37", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 50 fairies": {"id": 147, "level": "Fairy House", "cardName": "Psycho Dice", "isoAddress": "183A39", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 70 fairies": {"id": 148, "level": "Fairy House", "cardName": "Whip Worm", "isoAddress": "183A3B", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 80 fairies": {"id": 149, "level": "Fairy House", "cardName": "Global Bust", "isoAddress": "183A3D", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 90 fairies": {"id": 150, "level": "Fairy House", "cardName": "Crystal Magic", "isoAddress": "183A3F", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1},
    "collect 100 fairies": {"id": 151, "level": "Fairy House", "cardName": "Circasaurus", "isoAddress": "183A41", "missable": 1, "RAMAddress": "", "type": "Chest", "bitOffset": -1}
}

lost_kingdoms_2_regions = [
    "Nobleman's Residence",
    "Bhashea High Road",
    "Kadishu",
    "Bhashea Castle",
    "Gromtull Desert",
    "Kendarie Fortress",
    "Runestone Caverns - Upper Chambers",
    "Runestone Caverns - Lower Chambers",
    "Ruldo Forest",
    "Sacred Battle Arena 1",
    "Sacred Battle Arena 2",
    "Fossil Boneyard",
    "Sarvan",
    "Holzogh Town",
    "Plains of Rowahl",
    "Alanjeh Castle",
    "Royal Tower, Lower",
    "Royal Tower, Middle",
    "Royal Tower, Upper",
    "Krasheen Mountains",
    "Grenfoel Church",
    "Temple of Sharacia",
    "Isamat Urbur",
    "Obenoix Gorge",
    "Fairy House",
]